namespace MakoCelo
{
	// Token: 0x02000009 RID: 9
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmLabelSetup : global::System.Windows.Forms.Form
	{
		// Token: 0x06000015 RID: 21 RVA: 0x00002278 File Offset: 0x00000478
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000016 RID: 22 RVA: 0x000022B8 File Offset: 0x000004B8
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::MakoCelo.frmLabelSetup));
			this.gbLabel = new global::System.Windows.Forms.GroupBox();
			this.cboDepth = new global::System.Windows.Forms.ComboBox();
			this.lbDepth = new global::System.Windows.Forms.Label();
			this.tbHeight = new global::System.Windows.Forms.TextBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.tbWidth = new global::System.Windows.Forms.TextBox();
			this.lbSize = new global::System.Windows.Forms.Label();
			this.cmShadowColor = new global::System.Windows.Forms.Button();
			this.lbR5 = new global::System.Windows.Forms.Label();
			this.cbo3D = new global::System.Windows.Forms.ComboBox();
			this.cboA2 = new global::System.Windows.Forms.ComboBox();
			this.lbR4 = new global::System.Windows.Forms.Label();
			this.cmBR = new global::System.Windows.Forms.Button();
			this.cmBD = new global::System.Windows.Forms.Button();
			this.cmFR = new global::System.Windows.Forms.Button();
			this.cmFD = new global::System.Windows.Forms.Button();
			this.cmB2 = new global::System.Windows.Forms.Button();
			this.cmB1 = new global::System.Windows.Forms.Button();
			this.lbR2 = new global::System.Windows.Forms.Label();
			this.cmF2 = new global::System.Windows.Forms.Button();
			this.cmRankFont = new global::System.Windows.Forms.Button();
			this.cmF1 = new global::System.Windows.Forms.Button();
			this.lbR1 = new global::System.Windows.Forms.Label();
			this.lbR3 = new global::System.Windows.Forms.Label();
			this.cboA1 = new global::System.Windows.Forms.ComboBox();
			this.pbNote = new global::System.Windows.Forms.PictureBox();
			this.cmCancel = new global::System.Windows.Forms.Button();
			this.cmOK = new global::System.Windows.Forms.Button();
			this.ColorDialog1 = new global::System.Windows.Forms.ColorDialog();
			this.gbBack = new global::System.Windows.Forms.GroupBox();
			this.cboScaling = new global::System.Windows.Forms.ComboBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.cmFormColor = new global::System.Windows.Forms.Button();
			this.cmFormImage = new global::System.Windows.Forms.Button();
			this.cmNoImage = new global::System.Windows.Forms.Button();
			this.cboOVLScaling = new global::System.Windows.Forms.ComboBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.cmOverlay = new global::System.Windows.Forms.Button();
			this.cmCopy01 = new global::System.Windows.Forms.Button();
			this.cmCopy02 = new global::System.Windows.Forms.Button();
			this.cmCopy03 = new global::System.Windows.Forms.Button();
			this.cmCopy04 = new global::System.Windows.Forms.Button();
			this.cmCopyAll = new global::System.Windows.Forms.Button();
			this.cmCopySize = new global::System.Windows.Forms.Button();
			this.cmOVLNoImage = new global::System.Windows.Forms.Button();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.ToolTip1 = new global::System.Windows.Forms.ToolTip(this.components);
			this.gbLabel.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.pbNote).BeginInit();
			this.gbBack.SuspendLayout();
			this.GroupBox1.SuspendLayout();
			base.SuspendLayout();
			this.gbLabel.Controls.Add(this.cboDepth);
			this.gbLabel.Controls.Add(this.lbDepth);
			this.gbLabel.Controls.Add(this.tbHeight);
			this.gbLabel.Controls.Add(this.Label1);
			this.gbLabel.Controls.Add(this.tbWidth);
			this.gbLabel.Controls.Add(this.lbSize);
			this.gbLabel.Controls.Add(this.cmShadowColor);
			this.gbLabel.Controls.Add(this.lbR5);
			this.gbLabel.Controls.Add(this.cbo3D);
			this.gbLabel.Controls.Add(this.cboA2);
			this.gbLabel.Controls.Add(this.lbR4);
			this.gbLabel.Controls.Add(this.cmBR);
			this.gbLabel.Controls.Add(this.cmBD);
			this.gbLabel.Controls.Add(this.cmFR);
			this.gbLabel.Controls.Add(this.cmFD);
			this.gbLabel.Controls.Add(this.cmB2);
			this.gbLabel.Controls.Add(this.cmB1);
			this.gbLabel.Controls.Add(this.lbR2);
			this.gbLabel.Controls.Add(this.cmF2);
			this.gbLabel.Controls.Add(this.cmRankFont);
			this.gbLabel.Controls.Add(this.cmF1);
			this.gbLabel.Controls.Add(this.lbR1);
			this.gbLabel.Controls.Add(this.lbR3);
			this.gbLabel.Controls.Add(this.cboA1);
			this.gbLabel.ForeColor = global::System.Drawing.Color.Black;
			this.gbLabel.Location = new global::System.Drawing.Point(10, 10);
			this.gbLabel.Name = "gbLabel";
			this.gbLabel.Size = new global::System.Drawing.Size(256, 247);
			this.gbLabel.TabIndex = 74;
			this.gbLabel.TabStop = false;
			this.gbLabel.Text = "Text Setup";
			this.cboDepth.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cboDepth.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboDepth.ForeColor = global::System.Drawing.Color.White;
			this.cboDepth.FormattingEnabled = true;
			this.cboDepth.Location = new global::System.Drawing.Point(200, 135);
			this.cboDepth.Name = "cboDepth";
			this.cboDepth.Size = new global::System.Drawing.Size(46, 21);
			this.cboDepth.TabIndex = 13;
			this.lbDepth.AutoSize = true;
			this.lbDepth.Location = new global::System.Drawing.Point(5, 135);
			this.lbDepth.Name = "lbDepth";
			this.lbDepth.Size = new global::System.Drawing.Size(78, 13);
			this.lbDepth.TabIndex = 143;
			this.lbDepth.Text = "Shadow Depth";
			this.tbHeight.BackColor = global::System.Drawing.Color.White;
			this.tbHeight.ForeColor = global::System.Drawing.Color.Black;
			this.tbHeight.Location = new global::System.Drawing.Point(130, 220);
			this.tbHeight.Name = "tbHeight";
			this.tbHeight.Size = new global::System.Drawing.Size(118, 20);
			this.tbHeight.TabIndex = 16;
			this.Label1.AutoSize = true;
			this.Label1.Location = new global::System.Drawing.Point(10, 225);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(107, 13);
			this.Label1.TabIndex = 141;
			this.Label1.Text = "Note Height (60 max)";
			this.tbWidth.BackColor = global::System.Drawing.Color.White;
			this.tbWidth.ForeColor = global::System.Drawing.Color.Black;
			this.tbWidth.Location = new global::System.Drawing.Point(130, 195);
			this.tbWidth.Name = "tbWidth";
			this.tbWidth.Size = new global::System.Drawing.Size(118, 20);
			this.tbWidth.TabIndex = 15;
			this.lbSize.AutoSize = true;
			this.lbSize.Location = new global::System.Drawing.Point(10, 200);
			this.lbSize.Name = "lbSize";
			this.lbSize.Size = new global::System.Drawing.Size(61, 13);
			this.lbSize.TabIndex = 137;
			this.lbSize.Text = "Note Width";
			this.cmShadowColor.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmShadowColor.Location = new global::System.Drawing.Point(174, 111);
			this.cmShadowColor.Name = "cmShadowColor";
			this.cmShadowColor.Size = new global::System.Drawing.Size(21, 21);
			this.cmShadowColor.TabIndex = 11;
			this.cmShadowColor.Text = "1";
			this.cmShadowColor.UseVisualStyleBackColor = true;
			this.lbR5.AutoSize = true;
			this.lbR5.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.lbR5.Location = new global::System.Drawing.Point(5, 110);
			this.lbR5.Name = "lbR5";
			this.lbR5.Size = new global::System.Drawing.Size(119, 13);
			this.lbR5.TabIndex = 67;
			this.lbR5.Text = "Simple Shadow Options";
			this.cbo3D.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cbo3D.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cbo3D.ForeColor = global::System.Drawing.Color.White;
			this.cbo3D.FormattingEnabled = true;
			this.cbo3D.Location = new global::System.Drawing.Point(200, 110);
			this.cbo3D.Name = "cbo3D";
			this.cbo3D.Size = new global::System.Drawing.Size(46, 21);
			this.cbo3D.TabIndex = 12;
			this.cboA2.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cboA2.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboA2.ForeColor = global::System.Drawing.Color.White;
			this.cboA2.FormattingEnabled = true;
			this.cboA2.Location = new global::System.Drawing.Point(175, 85);
			this.cboA2.Name = "cboA2";
			this.cboA2.Size = new global::System.Drawing.Size(71, 21);
			this.cboA2.TabIndex = 10;
			this.lbR4.AutoSize = true;
			this.lbR4.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.lbR4.Location = new global::System.Drawing.Point(5, 85);
			this.lbR4.Name = "lbR4";
			this.lbR4.Size = new global::System.Drawing.Size(156, 13);
			this.lbR4.TabIndex = 64;
			this.lbR4.Text = "Background Gradient Opacity 2";
			this.cmBR.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmBR.Location = new global::System.Drawing.Point(225, 34);
			this.cmBR.Name = "cmBR";
			this.cmBR.Size = new global::System.Drawing.Size(20, 21);
			this.cmBR.TabIndex = 8;
			this.cmBR.Text = ">";
			this.cmBR.UseVisualStyleBackColor = true;
			this.cmBD.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmBD.Location = new global::System.Drawing.Point(200, 34);
			this.cmBD.Name = "cmBD";
			this.cmBD.Size = new global::System.Drawing.Size(20, 21);
			this.cmBD.TabIndex = 7;
			this.cmBD.Text = "˅";
			this.cmBD.UseVisualStyleBackColor = true;
			this.cmFR.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmFR.Location = new global::System.Drawing.Point(225, 10);
			this.cmFR.Name = "cmFR";
			this.cmFR.Size = new global::System.Drawing.Size(20, 21);
			this.cmFR.TabIndex = 4;
			this.cmFR.Text = ">";
			this.cmFR.UseVisualStyleBackColor = true;
			this.cmFD.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmFD.Location = new global::System.Drawing.Point(200, 10);
			this.cmFD.Name = "cmFD";
			this.cmFD.Size = new global::System.Drawing.Size(20, 21);
			this.cmFD.TabIndex = 3;
			this.cmFD.Text = "˅";
			this.cmFD.UseVisualStyleBackColor = true;
			this.cmB2.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmB2.Location = new global::System.Drawing.Point(175, 34);
			this.cmB2.Name = "cmB2";
			this.cmB2.Size = new global::System.Drawing.Size(20, 21);
			this.cmB2.TabIndex = 6;
			this.cmB2.Text = "2";
			this.cmB2.UseVisualStyleBackColor = true;
			this.cmB1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmB1.Location = new global::System.Drawing.Point(150, 34);
			this.cmB1.Name = "cmB1";
			this.cmB1.Size = new global::System.Drawing.Size(20, 21);
			this.cmB1.TabIndex = 5;
			this.cmB1.Text = "1";
			this.cmB1.UseVisualStyleBackColor = true;
			this.lbR2.AutoSize = true;
			this.lbR2.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.lbR2.Location = new global::System.Drawing.Point(5, 35);
			this.lbR2.Name = "lbR2";
			this.lbR2.Size = new global::System.Drawing.Size(135, 13);
			this.lbR2.TabIndex = 57;
			this.lbR2.Text = "Background Gradient Color";
			this.cmF2.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmF2.Location = new global::System.Drawing.Point(175, 10);
			this.cmF2.Name = "cmF2";
			this.cmF2.Size = new global::System.Drawing.Size(20, 21);
			this.cmF2.TabIndex = 2;
			this.cmF2.Text = "2";
			this.cmF2.UseVisualStyleBackColor = true;
			this.cmRankFont.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmRankFont.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmRankFont.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmRankFont.ForeColor = global::System.Drawing.Color.Black;
			this.cmRankFont.Location = new global::System.Drawing.Point(175, 160);
			this.cmRankFont.Name = "cmRankFont";
			this.cmRankFont.Size = new global::System.Drawing.Size(70, 26);
			this.cmRankFont.TabIndex = 14;
			this.cmRankFont.Text = "Font";
			this.cmRankFont.UseVisualStyleBackColor = false;
			this.cmF1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmF1.Location = new global::System.Drawing.Point(150, 10);
			this.cmF1.Name = "cmF1";
			this.cmF1.Size = new global::System.Drawing.Size(20, 21);
			this.cmF1.TabIndex = 1;
			this.cmF1.Text = "1";
			this.cmF1.UseVisualStyleBackColor = true;
			this.lbR1.AutoSize = true;
			this.lbR1.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.lbR1.Location = new global::System.Drawing.Point(5, 15);
			this.lbR1.Name = "lbR1";
			this.lbR1.Size = new global::System.Drawing.Size(98, 13);
			this.lbR1.TabIndex = 54;
			this.lbR1.Text = "Font Gradient Color";
			this.lbR3.AutoSize = true;
			this.lbR3.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.lbR3.Location = new global::System.Drawing.Point(5, 60);
			this.lbR3.Name = "lbR3";
			this.lbR3.Size = new global::System.Drawing.Size(156, 13);
			this.lbR3.TabIndex = 53;
			this.lbR3.Text = "Background Gradient Opacity 1";
			this.cboA1.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cboA1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboA1.ForeColor = global::System.Drawing.Color.White;
			this.cboA1.FormattingEnabled = true;
			this.cboA1.Location = new global::System.Drawing.Point(175, 60);
			this.cboA1.Name = "cboA1";
			this.cboA1.Size = new global::System.Drawing.Size(71, 21);
			this.cboA1.TabIndex = 9;
			this.pbNote.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.pbNote.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.pbNote.Location = new global::System.Drawing.Point(12, 275);
			this.pbNote.Name = "pbNote";
			this.pbNote.Size = new global::System.Drawing.Size(256, 40);
			this.pbNote.TabIndex = 92;
			this.pbNote.TabStop = false;
			this.cmCancel.Location = new global::System.Drawing.Point(445, 60);
			this.cmCancel.Name = "cmCancel";
			this.cmCancel.Size = new global::System.Drawing.Size(120, 37);
			this.cmCancel.TabIndex = 25;
			this.cmCancel.Text = "Cancel";
			this.cmCancel.UseVisualStyleBackColor = true;
			this.cmOK.Location = new global::System.Drawing.Point(445, 15);
			this.cmOK.Name = "cmOK";
			this.cmOK.Size = new global::System.Drawing.Size(120, 37);
			this.cmOK.TabIndex = 24;
			this.cmOK.Text = "OK";
			this.cmOK.UseVisualStyleBackColor = true;
			this.gbBack.Controls.Add(this.cboScaling);
			this.gbBack.Controls.Add(this.Label7);
			this.gbBack.Controls.Add(this.cmFormColor);
			this.gbBack.Controls.Add(this.cmFormImage);
			this.gbBack.Controls.Add(this.cmNoImage);
			this.gbBack.Location = new global::System.Drawing.Point(275, 10);
			this.gbBack.Name = "gbBack";
			this.gbBack.Size = new global::System.Drawing.Size(130, 135);
			this.gbBack.TabIndex = 135;
			this.gbBack.TabStop = false;
			this.gbBack.Text = "Background";
			this.cboScaling.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cboScaling.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboScaling.ForeColor = global::System.Drawing.Color.White;
			this.cboScaling.FormattingEnabled = true;
			this.cboScaling.Location = new global::System.Drawing.Point(50, 105);
			this.cboScaling.Name = "cboScaling";
			this.cboScaling.Size = new global::System.Drawing.Size(70, 21);
			this.cboScaling.TabIndex = 20;
			this.Label7.AutoSize = true;
			this.Label7.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.Label7.Location = new global::System.Drawing.Point(5, 110);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(42, 13);
			this.Label7.TabIndex = 64;
			this.Label7.Text = "Scaling";
			this.cmFormColor.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmFormColor.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmFormColor.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmFormColor.ForeColor = global::System.Drawing.Color.Black;
			this.cmFormColor.Location = new global::System.Drawing.Point(5, 15);
			this.cmFormColor.Name = "cmFormColor";
			this.cmFormColor.Size = new global::System.Drawing.Size(115, 26);
			this.cmFormColor.TabIndex = 17;
			this.cmFormColor.Text = "Panel Color";
			this.cmFormColor.UseVisualStyleBackColor = false;
			this.cmFormImage.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmFormImage.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmFormImage.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmFormImage.ForeColor = global::System.Drawing.Color.Black;
			this.cmFormImage.Location = new global::System.Drawing.Point(5, 75);
			this.cmFormImage.Name = "cmFormImage";
			this.cmFormImage.Size = new global::System.Drawing.Size(115, 26);
			this.cmFormImage.TabIndex = 19;
			this.cmFormImage.Text = "Panel Image";
			this.cmFormImage.UseVisualStyleBackColor = false;
			this.cmNoImage.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmNoImage.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmNoImage.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmNoImage.ForeColor = global::System.Drawing.Color.Black;
			this.cmNoImage.Location = new global::System.Drawing.Point(5, 45);
			this.cmNoImage.Name = "cmNoImage";
			this.cmNoImage.Size = new global::System.Drawing.Size(115, 26);
			this.cmNoImage.TabIndex = 18;
			this.cmNoImage.Text = "No Image";
			this.cmNoImage.UseVisualStyleBackColor = false;
			this.cboOVLScaling.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cboOVLScaling.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboOVLScaling.ForeColor = global::System.Drawing.Color.White;
			this.cboOVLScaling.FormattingEnabled = true;
			this.cboOVLScaling.Location = new global::System.Drawing.Point(50, 75);
			this.cboOVLScaling.Name = "cboOVLScaling";
			this.cboOVLScaling.Size = new global::System.Drawing.Size(73, 21);
			this.cboOVLScaling.TabIndex = 23;
			this.Label2.AutoSize = true;
			this.Label2.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.Label2.Location = new global::System.Drawing.Point(5, 80);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(42, 13);
			this.Label2.TabIndex = 66;
			this.Label2.Text = "Scaling";
			this.cmOverlay.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmOverlay.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmOverlay.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmOverlay.ForeColor = global::System.Drawing.Color.Black;
			this.cmOverlay.Location = new global::System.Drawing.Point(5, 45);
			this.cmOverlay.Name = "cmOverlay";
			this.cmOverlay.Size = new global::System.Drawing.Size(118, 26);
			this.cmOverlay.TabIndex = 22;
			this.cmOverlay.Text = "Overlay Image";
			this.cmOverlay.UseVisualStyleBackColor = false;
			this.cmCopy01.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmCopy01.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmCopy01.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmCopy01.ForeColor = global::System.Drawing.Color.Black;
			this.cmCopy01.Location = new global::System.Drawing.Point(430, 120);
			this.cmCopy01.Name = "cmCopy01";
			this.cmCopy01.Size = new global::System.Drawing.Size(145, 26);
			this.cmCopy01.TabIndex = 26;
			this.cmCopy01.Text = "Copy Note 1 settings";
			this.cmCopy01.UseVisualStyleBackColor = false;
			this.cmCopy02.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmCopy02.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmCopy02.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmCopy02.ForeColor = global::System.Drawing.Color.Black;
			this.cmCopy02.Location = new global::System.Drawing.Point(430, 150);
			this.cmCopy02.Name = "cmCopy02";
			this.cmCopy02.Size = new global::System.Drawing.Size(145, 26);
			this.cmCopy02.TabIndex = 27;
			this.cmCopy02.Text = "Copy Note 2 settings";
			this.cmCopy02.UseVisualStyleBackColor = false;
			this.cmCopy03.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmCopy03.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmCopy03.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmCopy03.ForeColor = global::System.Drawing.Color.Black;
			this.cmCopy03.Location = new global::System.Drawing.Point(430, 180);
			this.cmCopy03.Name = "cmCopy03";
			this.cmCopy03.Size = new global::System.Drawing.Size(145, 26);
			this.cmCopy03.TabIndex = 28;
			this.cmCopy03.Text = "Copy Note 3 settings";
			this.cmCopy03.UseVisualStyleBackColor = false;
			this.cmCopy04.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmCopy04.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmCopy04.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmCopy04.ForeColor = global::System.Drawing.Color.Black;
			this.cmCopy04.Location = new global::System.Drawing.Point(430, 210);
			this.cmCopy04.Name = "cmCopy04";
			this.cmCopy04.Size = new global::System.Drawing.Size(145, 26);
			this.cmCopy04.TabIndex = 29;
			this.cmCopy04.Text = "Copy Note 4 settings";
			this.cmCopy04.UseVisualStyleBackColor = false;
			this.cmCopyAll.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmCopyAll.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmCopyAll.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmCopyAll.ForeColor = global::System.Drawing.Color.Black;
			this.cmCopyAll.Location = new global::System.Drawing.Point(430, 255);
			this.cmCopyAll.Name = "cmCopyAll";
			this.cmCopyAll.Size = new global::System.Drawing.Size(145, 26);
			this.cmCopyAll.TabIndex = 30;
			this.cmCopyAll.Text = "Set ALL notes to this Style";
			this.cmCopyAll.UseVisualStyleBackColor = false;
			this.cmCopySize.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmCopySize.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmCopySize.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmCopySize.ForeColor = global::System.Drawing.Color.Black;
			this.cmCopySize.Location = new global::System.Drawing.Point(430, 285);
			this.cmCopySize.Name = "cmCopySize";
			this.cmCopySize.Size = new global::System.Drawing.Size(145, 26);
			this.cmCopySize.TabIndex = 31;
			this.cmCopySize.Text = "Set ALL notes to this Size";
			this.cmCopySize.UseVisualStyleBackColor = false;
			this.cmOVLNoImage.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmOVLNoImage.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmOVLNoImage.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmOVLNoImage.ForeColor = global::System.Drawing.Color.Black;
			this.cmOVLNoImage.Location = new global::System.Drawing.Point(5, 15);
			this.cmOVLNoImage.Name = "cmOVLNoImage";
			this.cmOVLNoImage.Size = new global::System.Drawing.Size(118, 26);
			this.cmOVLNoImage.TabIndex = 21;
			this.cmOVLNoImage.Text = "No Image";
			this.cmOVLNoImage.UseVisualStyleBackColor = false;
			this.GroupBox1.Controls.Add(this.cmOVLNoImage);
			this.GroupBox1.Controls.Add(this.cmOverlay);
			this.GroupBox1.Controls.Add(this.cboOVLScaling);
			this.GroupBox1.Controls.Add(this.Label2);
			this.GroupBox1.Location = new global::System.Drawing.Point(275, 145);
			this.GroupBox1.Name = "GroupBox1";
			this.GroupBox1.Size = new global::System.Drawing.Size(130, 110);
			this.GroupBox1.TabIndex = 143;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Overlay";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(599, 344);
			base.Controls.Add(this.GroupBox1);
			base.Controls.Add(this.cmCopySize);
			base.Controls.Add(this.cmCopyAll);
			base.Controls.Add(this.cmCopy04);
			base.Controls.Add(this.cmCopy03);
			base.Controls.Add(this.cmCopy02);
			base.Controls.Add(this.cmCopy01);
			base.Controls.Add(this.gbBack);
			base.Controls.Add(this.cmCancel);
			base.Controls.Add(this.cmOK);
			base.Controls.Add(this.pbNote);
			base.Controls.Add(this.gbLabel);
			this.DoubleBuffered = true;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "frmLabelSetup";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Text Object Setup";
			this.gbLabel.ResumeLayout(false);
			this.gbLabel.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.pbNote).EndInit();
			this.gbBack.ResumeLayout(false);
			this.gbBack.PerformLayout();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			base.ResumeLayout(false);
		}

		// Token: 0x0400000B RID: 11
		private global::System.ComponentModel.IContainer components;
	}
}
