namespace MakoCelo
{
	// Token: 0x0200000C RID: 12
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmMain : global::System.Windows.Forms.Form
	{
		// Token: 0x060001D2 RID: 466 RVA: 0x0001D094 File Offset: 0x0001B294
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060001D3 RID: 467 RVA: 0x0001D0D4 File Offset: 0x0001B2D4
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::MakoCelo.frmMain));
			this.cmCheckLog = new global::System.Windows.Forms.Button();
			this.lbStatus = new global::System.Windows.Forms.Label();
			this.pbFact01 = new global::System.Windows.Forms.PictureBox();
			this.pbFact02 = new global::System.Windows.Forms.PictureBox();
			this.pbFact03 = new global::System.Windows.Forms.PictureBox();
			this.pbFact04 = new global::System.Windows.Forms.PictureBox();
			this.pbFact05 = new global::System.Windows.Forms.PictureBox();
			this.lbSteam01 = new global::System.Windows.Forms.Label();
			this.lbSteam02 = new global::System.Windows.Forms.Label();
			this.lbSteam03 = new global::System.Windows.Forms.Label();
			this.lbSteam04 = new global::System.Windows.Forms.Label();
			this.lbSteam05 = new global::System.Windows.Forms.Label();
			this.lbSteam06 = new global::System.Windows.Forms.Label();
			this.lbSteam07 = new global::System.Windows.Forms.Label();
			this.lbSteam08 = new global::System.Windows.Forms.Label();
			this.ColorDialog1 = new global::System.Windows.Forms.ColorDialog();
			this.OpenFileDialog1 = new global::System.Windows.Forms.OpenFileDialog();
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.cmFindLog = new global::System.Windows.Forms.Button();
			this.cmScanLog = new global::System.Windows.Forms.Button();
			this.cmCopy = new global::System.Windows.Forms.Button();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.FontDialog1 = new global::System.Windows.Forms.FontDialog();
			this.cmAbout = new global::System.Windows.Forms.Button();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.cboLayoutY = new global::System.Windows.Forms.ComboBox();
			this.gbRank = new global::System.Windows.Forms.GroupBox();
			this.cmNote_PlayAll = new global::System.Windows.Forms.Button();
			this.cmNote04_Play = new global::System.Windows.Forms.Button();
			this.cmNote03_Play = new global::System.Windows.Forms.Button();
			this.cmNote02_Play = new global::System.Windows.Forms.Button();
			this.cmNote01_Play = new global::System.Windows.Forms.Button();
			this.cmNote4 = new global::System.Windows.Forms.Button();
			this.cmNote04Setup = new global::System.Windows.Forms.Button();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.cmNote3 = new global::System.Windows.Forms.Button();
			this.cmNote2 = new global::System.Windows.Forms.Button();
			this.cmNote1 = new global::System.Windows.Forms.Button();
			this.cmNote03Setup = new global::System.Windows.Forms.Button();
			this.cmNote02Setup = new global::System.Windows.Forms.Button();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.cmNote01Setup = new global::System.Windows.Forms.Button();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.cmNameSetup = new global::System.Windows.Forms.Button();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.cmRankSetup = new global::System.Windows.Forms.Button();
			this.cmSave = new global::System.Windows.Forms.Button();
			this.gbLayout = new global::System.Windows.Forms.GroupBox();
			this.cmStatsModeHelp = new global::System.Windows.Forms.Button();
			this.cmDefaults = new global::System.Windows.Forms.Button();
			this.tbYSize = new global::System.Windows.Forms.TextBox();
			this.tbXsize = new global::System.Windows.Forms.TextBox();
			this.tbYoff = new global::System.Windows.Forms.TextBox();
			this.tbXoff = new global::System.Windows.Forms.TextBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.cboNoteSpace = new global::System.Windows.Forms.ComboBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.cmSizeRefresh = new global::System.Windows.Forms.Button();
			this.cboLayoutX = new global::System.Windows.Forms.ComboBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.cmGUIDark = new global::System.Windows.Forms.Button();
			this.cmGUILite = new global::System.Windows.Forms.Button();
			this.pbStats = new global::System.Windows.Forms.PictureBox();
			this.cmTestData = new global::System.Windows.Forms.Button();
			this.cmLastMatch = new global::System.Windows.Forms.Button();
			this.gbFX = new global::System.Windows.Forms.GroupBox();
			this.chkFX = new global::System.Windows.Forms.CheckBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.cmFXModeHelp = new global::System.Windows.Forms.Button();
			this.cboFXVar1 = new global::System.Windows.Forms.ComboBox();
			this.lbFXVar1 = new global::System.Windows.Forms.Label();
			this.cboFxVar3 = new global::System.Windows.Forms.ComboBox();
			this.lbFXVar3 = new global::System.Windows.Forms.Label();
			this.cboFxVar4 = new global::System.Windows.Forms.ComboBox();
			this.cmFX3DC = new global::System.Windows.Forms.Button();
			this.cboFXVar2 = new global::System.Windows.Forms.ComboBox();
			this.lbFXVar2 = new global::System.Windows.Forms.Label();
			this.lbFXVar4 = new global::System.Windows.Forms.Label();
			this.lbError1 = new global::System.Windows.Forms.Label();
			this.lbError2 = new global::System.Windows.Forms.Label();
			this.SaveFileDialog1 = new global::System.Windows.Forms.SaveFileDialog();
			this.chkMismatch = new global::System.Windows.Forms.CheckBox();
			this.ToolTip1 = new global::System.Windows.Forms.ToolTip(this.components);
			this.chkTips = new global::System.Windows.Forms.CheckBox();
			this.pbNote1 = new global::System.Windows.Forms.PictureBox();
			this.timNote1 = new global::System.Windows.Forms.Timer(this.components);
			this.gbSound = new global::System.Windows.Forms.GroupBox();
			this.cmAudioStop = new global::System.Windows.Forms.Button();
			this.lbVolume = new global::System.Windows.Forms.Label();
			this.scrVolume = new global::System.Windows.Forms.HScrollBar();
			this.cmSound15 = new global::System.Windows.Forms.Button();
			this.cmSound14 = new global::System.Windows.Forms.Button();
			this.cmSound13 = new global::System.Windows.Forms.Button();
			this.cmSound12 = new global::System.Windows.Forms.Button();
			this.cmSound11 = new global::System.Windows.Forms.Button();
			this.lbSoundCurrent = new global::System.Windows.Forms.Label();
			this.cmSound10 = new global::System.Windows.Forms.Button();
			this.cmSound09 = new global::System.Windows.Forms.Button();
			this.cmSound08 = new global::System.Windows.Forms.Button();
			this.cmSound07 = new global::System.Windows.Forms.Button();
			this.cmSound06 = new global::System.Windows.Forms.Button();
			this.cmSound05 = new global::System.Windows.Forms.Button();
			this.cmSound04 = new global::System.Windows.Forms.Button();
			this.cmSound03 = new global::System.Windows.Forms.Button();
			this.cmSound02 = new global::System.Windows.Forms.Button();
			this.cmSound01 = new global::System.Windows.Forms.Button();
			this.pbNote3 = new global::System.Windows.Forms.PictureBox();
			this.pbNote4 = new global::System.Windows.Forms.PictureBox();
			this.pbNote2 = new global::System.Windows.Forms.PictureBox();
			this.chkPosition = new global::System.Windows.Forms.CheckBox();
			this.tsmPlayer = new global::System.Windows.Forms.ContextMenuStrip(this.components);
			this.tsmPlayer_Relic = new global::System.Windows.Forms.ToolStripMenuItem();
			this.tsmPlayer_OrgAT = new global::System.Windows.Forms.ToolStripMenuItem();
			this.tsmPlayer_OrgFaction = new global::System.Windows.Forms.ToolStripMenuItem();
			this.tsmPlayer_OrgPlayercard = new global::System.Windows.Forms.ToolStripMenuItem();
			this.tsmPlayer_Google = new global::System.Windows.Forms.ToolStripMenuItem();
			this.chkPopUp = new global::System.Windows.Forms.CheckBox();
			this.tsmAudio = new global::System.Windows.Forms.ContextMenuStrip(this.components);
			this.tsmSetVolTo100 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.tsmSetVolTo90 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.tsmSetVolTo80 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.tsmSetVolTo70 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.tsmSetVolTo60 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.tsmSetVolTo50 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.tsmSetVolTo40 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.tsmSetVolTo30 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.tsmSetVolTo20 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.tsmSetVolTo10 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripMenuItem1 = new global::System.Windows.Forms.ToolStripSeparator();
			this.tsmSelectFile = new global::System.Windows.Forms.ToolStripMenuItem();
			this.chkSmoothAni = new global::System.Windows.Forms.CheckBox();
			((global::System.ComponentModel.ISupportInitialize)this.pbFact01).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.pbFact02).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.pbFact03).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.pbFact04).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.pbFact05).BeginInit();
			this.gbRank.SuspendLayout();
			this.gbLayout.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.pbStats).BeginInit();
			this.gbFX.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.pbNote1).BeginInit();
			this.gbSound.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.pbNote3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.pbNote4).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.pbNote2).BeginInit();
			this.tsmPlayer.SuspendLayout();
			this.tsmAudio.SuspendLayout();
			base.SuspendLayout();
			this.cmCheckLog.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmCheckLog.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmCheckLog.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmCheckLog.ForeColor = global::System.Drawing.Color.Black;
			this.cmCheckLog.Location = new global::System.Drawing.Point(10, 35);
			this.cmCheckLog.Name = "cmCheckLog";
			this.cmCheckLog.Size = new global::System.Drawing.Size(111, 30);
			this.cmCheckLog.TabIndex = 1;
			this.cmCheckLog.Text = "Check Log File";
			this.cmCheckLog.UseVisualStyleBackColor = false;
			this.lbStatus.BackColor = global::System.Drawing.Color.Silver;
			this.lbStatus.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.lbStatus.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lbStatus.ForeColor = global::System.Drawing.Color.Black;
			this.lbStatus.Location = new global::System.Drawing.Point(880, 15);
			this.lbStatus.Name = "lbStatus";
			this.lbStatus.Size = new global::System.Drawing.Size(235, 18);
			this.lbStatus.TabIndex = 25;
			this.lbStatus.Text = "Ready.";
			this.lbStatus.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.pbFact01.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.None;
			this.pbFact01.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("pbFact01.Image");
			this.pbFact01.Location = new global::System.Drawing.Point(1378, 192);
			this.pbFact01.Name = "pbFact01";
			this.pbFact01.Size = new global::System.Drawing.Size(95, 95);
			this.pbFact01.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.pbFact01.TabIndex = 26;
			this.pbFact01.TabStop = false;
			this.pbFact01.Visible = false;
			this.pbFact02.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.None;
			this.pbFact02.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("pbFact02.Image");
			this.pbFact02.Location = new global::System.Drawing.Point(1296, 192);
			this.pbFact02.Name = "pbFact02";
			this.pbFact02.Size = new global::System.Drawing.Size(95, 95);
			this.pbFact02.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.pbFact02.TabIndex = 27;
			this.pbFact02.TabStop = false;
			this.pbFact02.Visible = false;
			this.pbFact03.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.None;
			this.pbFact03.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("pbFact03.Image");
			this.pbFact03.Location = new global::System.Drawing.Point(1378, 279);
			this.pbFact03.Name = "pbFact03";
			this.pbFact03.Size = new global::System.Drawing.Size(95, 95);
			this.pbFact03.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.pbFact03.TabIndex = 28;
			this.pbFact03.TabStop = false;
			this.pbFact03.Visible = false;
			this.pbFact04.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.None;
			this.pbFact04.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("pbFact04.Image");
			this.pbFact04.Location = new global::System.Drawing.Point(1460, 279);
			this.pbFact04.Name = "pbFact04";
			this.pbFact04.Size = new global::System.Drawing.Size(95, 95);
			this.pbFact04.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.pbFact04.TabIndex = 29;
			this.pbFact04.TabStop = false;
			this.pbFact04.Visible = false;
			this.pbFact05.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.None;
			this.pbFact05.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("pbFact05.Image");
			this.pbFact05.Location = new global::System.Drawing.Point(1296, 279);
			this.pbFact05.Name = "pbFact05";
			this.pbFact05.Size = new global::System.Drawing.Size(95, 95);
			this.pbFact05.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.pbFact05.TabIndex = 30;
			this.pbFact05.TabStop = false;
			this.pbFact05.Visible = false;
			this.lbSteam01.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.lbSteam01.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lbSteam01.Location = new global::System.Drawing.Point(1465, 200);
			this.lbSteam01.Name = "lbSteam01";
			this.lbSteam01.Size = new global::System.Drawing.Size(50, 23);
			this.lbSteam01.TabIndex = 39;
			this.lbSteam01.Visible = false;
			this.lbSteam02.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.lbSteam02.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lbSteam02.Location = new global::System.Drawing.Point(1465, 223);
			this.lbSteam02.Name = "lbSteam02";
			this.lbSteam02.Size = new global::System.Drawing.Size(50, 23);
			this.lbSteam02.TabIndex = 40;
			this.lbSteam02.Visible = false;
			this.lbSteam03.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.lbSteam03.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lbSteam03.Location = new global::System.Drawing.Point(1465, 246);
			this.lbSteam03.Name = "lbSteam03";
			this.lbSteam03.Size = new global::System.Drawing.Size(50, 23);
			this.lbSteam03.TabIndex = 41;
			this.lbSteam03.Visible = false;
			this.lbSteam04.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.lbSteam04.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lbSteam04.Location = new global::System.Drawing.Point(1465, 269);
			this.lbSteam04.Name = "lbSteam04";
			this.lbSteam04.Size = new global::System.Drawing.Size(50, 23);
			this.lbSteam04.TabIndex = 42;
			this.lbSteam04.Visible = false;
			this.lbSteam05.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.lbSteam05.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lbSteam05.Location = new global::System.Drawing.Point(1519, 200);
			this.lbSteam05.Name = "lbSteam05";
			this.lbSteam05.Size = new global::System.Drawing.Size(50, 23);
			this.lbSteam05.TabIndex = 43;
			this.lbSteam05.Visible = false;
			this.lbSteam06.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.lbSteam06.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lbSteam06.Location = new global::System.Drawing.Point(1519, 223);
			this.lbSteam06.Name = "lbSteam06";
			this.lbSteam06.Size = new global::System.Drawing.Size(50, 23);
			this.lbSteam06.TabIndex = 44;
			this.lbSteam06.Visible = false;
			this.lbSteam07.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.lbSteam07.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lbSteam07.Location = new global::System.Drawing.Point(1519, 246);
			this.lbSteam07.Name = "lbSteam07";
			this.lbSteam07.Size = new global::System.Drawing.Size(50, 23);
			this.lbSteam07.TabIndex = 45;
			this.lbSteam07.Visible = false;
			this.lbSteam08.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.lbSteam08.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lbSteam08.Location = new global::System.Drawing.Point(1519, 269);
			this.lbSteam08.Name = "lbSteam08";
			this.lbSteam08.Size = new global::System.Drawing.Size(50, 23);
			this.lbSteam08.TabIndex = 46;
			this.lbSteam08.Visible = false;
			this.OpenFileDialog1.FileName = "OpenFileDialog1";
			this.Timer1.Interval = 1000;
			this.cmFindLog.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmFindLog.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmFindLog.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmFindLog.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.cmFindLog.ForeColor = global::System.Drawing.Color.Black;
			this.cmFindLog.Location = new global::System.Drawing.Point(10, 6);
			this.cmFindLog.Name = "cmFindLog";
			this.cmFindLog.Size = new global::System.Drawing.Size(111, 26);
			this.cmFindLog.TabIndex = 0;
			this.cmFindLog.Text = "Find Log File";
			this.cmFindLog.UseVisualStyleBackColor = false;
			this.cmScanLog.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmScanLog.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmScanLog.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmScanLog.ForeColor = global::System.Drawing.Color.Black;
			this.cmScanLog.Location = new global::System.Drawing.Point(10, 115);
			this.cmScanLog.Name = "cmScanLog";
			this.cmScanLog.Size = new global::System.Drawing.Size(111, 69);
			this.cmScanLog.TabIndex = 2;
			this.cmScanLog.Text = "Scan log every 10s";
			this.cmScanLog.UseVisualStyleBackColor = false;
			this.cmCopy.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmCopy.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmCopy.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmCopy.ForeColor = global::System.Drawing.Color.Black;
			this.cmCopy.Location = new global::System.Drawing.Point(880, 125);
			this.cmCopy.Name = "cmCopy";
			this.cmCopy.Size = new global::System.Drawing.Size(105, 26);
			this.cmCopy.TabIndex = 6;
			this.cmCopy.Text = "Copy Stats Image";
			this.cmCopy.UseVisualStyleBackColor = false;
			this.Label2.Location = new global::System.Drawing.Point(880, 0);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(235, 13);
			this.Label2.TabIndex = 61;
			this.Label2.Text = "Scan Status";
			this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.cmAbout.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmAbout.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmAbout.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmAbout.ForeColor = global::System.Drawing.Color.Black;
			this.cmAbout.Location = new global::System.Drawing.Point(880, 35);
			this.cmAbout.Name = "cmAbout";
			this.cmAbout.Size = new global::System.Drawing.Size(105, 26);
			this.cmAbout.TabIndex = 3;
			this.cmAbout.Text = "About";
			this.cmAbout.UseVisualStyleBackColor = false;
			this.Label3.AutoSize = true;
			this.Label3.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.Label3.Location = new global::System.Drawing.Point(5, 20);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(44, 13);
			this.Label3.TabIndex = 66;
			this.Label3.Text = "XY Size";
			this.Label4.AutoSize = true;
			this.Label4.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.Label4.Location = new global::System.Drawing.Point(5, 95);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(49, 13);
			this.Label4.TabIndex = 70;
			this.Label4.Text = "Y Layout";
			this.cboLayoutY.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cboLayoutY.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboLayoutY.ForeColor = global::System.Drawing.Color.White;
			this.cboLayoutY.FormattingEnabled = true;
			this.cboLayoutY.Location = new global::System.Drawing.Point(60, 90);
			this.cboLayoutY.Name = "cboLayoutY";
			this.cboLayoutY.Size = new global::System.Drawing.Size(126, 21);
			this.cboLayoutY.TabIndex = 23;
			this.gbRank.Controls.Add(this.cmNote_PlayAll);
			this.gbRank.Controls.Add(this.cmNote04_Play);
			this.gbRank.Controls.Add(this.cmNote03_Play);
			this.gbRank.Controls.Add(this.cmNote02_Play);
			this.gbRank.Controls.Add(this.cmNote01_Play);
			this.gbRank.Controls.Add(this.cmNote4);
			this.gbRank.Controls.Add(this.cmNote04Setup);
			this.gbRank.Controls.Add(this.Label14);
			this.gbRank.Controls.Add(this.cmNote3);
			this.gbRank.Controls.Add(this.cmNote2);
			this.gbRank.Controls.Add(this.cmNote1);
			this.gbRank.Controls.Add(this.cmNote03Setup);
			this.gbRank.Controls.Add(this.cmNote02Setup);
			this.gbRank.Controls.Add(this.Label13);
			this.gbRank.Controls.Add(this.Label12);
			this.gbRank.Controls.Add(this.cmNote01Setup);
			this.gbRank.Controls.Add(this.Label11);
			this.gbRank.Controls.Add(this.cmNameSetup);
			this.gbRank.Controls.Add(this.Label10);
			this.gbRank.Controls.Add(this.Label9);
			this.gbRank.Controls.Add(this.cmRankSetup);
			this.gbRank.ForeColor = global::System.Drawing.Color.Black;
			this.gbRank.Location = new global::System.Drawing.Point(130, 0);
			this.gbRank.Name = "gbRank";
			this.gbRank.Size = new global::System.Drawing.Size(198, 185);
			this.gbRank.TabIndex = 73;
			this.gbRank.TabStop = false;
			this.gbRank.Text = "Stats and Note Setups";
			this.cmNote_PlayAll.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmNote_PlayAll.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmNote_PlayAll.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmNote_PlayAll.ForeColor = global::System.Drawing.Color.Black;
			this.cmNote_PlayAll.Location = new global::System.Drawing.Point(155, 45);
			this.cmNote_PlayAll.Name = "cmNote_PlayAll";
			this.cmNote_PlayAll.Size = new global::System.Drawing.Size(30, 23);
			this.cmNote_PlayAll.TabIndex = 10;
			this.cmNote_PlayAll.Text = ">";
			this.cmNote_PlayAll.UseVisualStyleBackColor = false;
			this.cmNote04_Play.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmNote04_Play.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmNote04_Play.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmNote04_Play.ForeColor = global::System.Drawing.Color.Black;
			this.cmNote04_Play.Location = new global::System.Drawing.Point(155, 145);
			this.cmNote04_Play.Name = "cmNote04_Play";
			this.cmNote04_Play.Size = new global::System.Drawing.Size(30, 23);
			this.cmNote04_Play.TabIndex = 14;
			this.cmNote04_Play.Text = ">";
			this.cmNote04_Play.UseVisualStyleBackColor = false;
			this.cmNote03_Play.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmNote03_Play.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmNote03_Play.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmNote03_Play.ForeColor = global::System.Drawing.Color.Black;
			this.cmNote03_Play.Location = new global::System.Drawing.Point(155, 120);
			this.cmNote03_Play.Name = "cmNote03_Play";
			this.cmNote03_Play.Size = new global::System.Drawing.Size(30, 23);
			this.cmNote03_Play.TabIndex = 13;
			this.cmNote03_Play.Text = ">";
			this.cmNote03_Play.UseVisualStyleBackColor = false;
			this.cmNote02_Play.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmNote02_Play.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmNote02_Play.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmNote02_Play.ForeColor = global::System.Drawing.Color.Black;
			this.cmNote02_Play.Location = new global::System.Drawing.Point(155, 95);
			this.cmNote02_Play.Name = "cmNote02_Play";
			this.cmNote02_Play.Size = new global::System.Drawing.Size(30, 23);
			this.cmNote02_Play.TabIndex = 12;
			this.cmNote02_Play.Text = ">";
			this.cmNote02_Play.UseVisualStyleBackColor = false;
			this.cmNote01_Play.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmNote01_Play.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmNote01_Play.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmNote01_Play.ForeColor = global::System.Drawing.Color.Black;
			this.cmNote01_Play.Location = new global::System.Drawing.Point(155, 70);
			this.cmNote01_Play.Name = "cmNote01_Play";
			this.cmNote01_Play.Size = new global::System.Drawing.Size(30, 23);
			this.cmNote01_Play.TabIndex = 11;
			this.cmNote01_Play.Text = ">";
			this.cmNote01_Play.UseVisualStyleBackColor = false;
			this.cmNote4.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmNote4.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmNote4.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmNote4.ForeColor = global::System.Drawing.Color.Black;
			this.cmNote4.Location = new global::System.Drawing.Point(100, 145);
			this.cmNote4.Name = "cmNote4";
			this.cmNote4.Size = new global::System.Drawing.Size(50, 23);
			this.cmNote4.TabIndex = 9;
			this.cmNote4.Text = "Notes";
			this.cmNote4.UseVisualStyleBackColor = false;
			this.cmNote04Setup.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmNote04Setup.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmNote04Setup.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmNote04Setup.ForeColor = global::System.Drawing.Color.Black;
			this.cmNote04Setup.Location = new global::System.Drawing.Point(45, 145);
			this.cmNote04Setup.Name = "cmNote04Setup";
			this.cmNote04Setup.Size = new global::System.Drawing.Size(50, 23);
			this.cmNote04Setup.TabIndex = 8;
			this.cmNote04Setup.Text = "Setup";
			this.cmNote04Setup.UseVisualStyleBackColor = false;
			this.Label14.AutoSize = true;
			this.Label14.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.Label14.Location = new global::System.Drawing.Point(5, 150);
			this.Label14.Name = "Label14";
			this.Label14.Size = new global::System.Drawing.Size(39, 13);
			this.Label14.TabIndex = 123;
			this.Label14.Text = "Note 4";
			this.cmNote3.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmNote3.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmNote3.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmNote3.ForeColor = global::System.Drawing.Color.Black;
			this.cmNote3.Location = new global::System.Drawing.Point(100, 120);
			this.cmNote3.Name = "cmNote3";
			this.cmNote3.Size = new global::System.Drawing.Size(50, 23);
			this.cmNote3.TabIndex = 7;
			this.cmNote3.Text = "Notes";
			this.cmNote3.UseVisualStyleBackColor = false;
			this.cmNote2.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmNote2.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmNote2.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmNote2.ForeColor = global::System.Drawing.Color.Black;
			this.cmNote2.Location = new global::System.Drawing.Point(100, 95);
			this.cmNote2.Name = "cmNote2";
			this.cmNote2.Size = new global::System.Drawing.Size(50, 23);
			this.cmNote2.TabIndex = 5;
			this.cmNote2.Text = "Notes";
			this.cmNote2.UseVisualStyleBackColor = false;
			this.cmNote1.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmNote1.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmNote1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmNote1.ForeColor = global::System.Drawing.Color.Black;
			this.cmNote1.Location = new global::System.Drawing.Point(100, 70);
			this.cmNote1.Name = "cmNote1";
			this.cmNote1.Size = new global::System.Drawing.Size(50, 23);
			this.cmNote1.TabIndex = 3;
			this.cmNote1.Text = "Notes";
			this.cmNote1.UseVisualStyleBackColor = false;
			this.cmNote03Setup.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmNote03Setup.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmNote03Setup.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmNote03Setup.ForeColor = global::System.Drawing.Color.Black;
			this.cmNote03Setup.Location = new global::System.Drawing.Point(45, 120);
			this.cmNote03Setup.Name = "cmNote03Setup";
			this.cmNote03Setup.Size = new global::System.Drawing.Size(50, 23);
			this.cmNote03Setup.TabIndex = 6;
			this.cmNote03Setup.Text = "Setup";
			this.cmNote03Setup.UseVisualStyleBackColor = false;
			this.cmNote02Setup.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmNote02Setup.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmNote02Setup.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmNote02Setup.ForeColor = global::System.Drawing.Color.Black;
			this.cmNote02Setup.Location = new global::System.Drawing.Point(45, 95);
			this.cmNote02Setup.Name = "cmNote02Setup";
			this.cmNote02Setup.Size = new global::System.Drawing.Size(50, 23);
			this.cmNote02Setup.TabIndex = 4;
			this.cmNote02Setup.Text = "Setup";
			this.cmNote02Setup.UseVisualStyleBackColor = false;
			this.Label13.AutoSize = true;
			this.Label13.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.Label13.Location = new global::System.Drawing.Point(5, 125);
			this.Label13.Name = "Label13";
			this.Label13.Size = new global::System.Drawing.Size(39, 13);
			this.Label13.TabIndex = 117;
			this.Label13.Text = "Note 3";
			this.Label12.AutoSize = true;
			this.Label12.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.Label12.Location = new global::System.Drawing.Point(5, 100);
			this.Label12.Name = "Label12";
			this.Label12.Size = new global::System.Drawing.Size(39, 13);
			this.Label12.TabIndex = 116;
			this.Label12.Text = "Note 2";
			this.cmNote01Setup.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmNote01Setup.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmNote01Setup.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmNote01Setup.ForeColor = global::System.Drawing.Color.Black;
			this.cmNote01Setup.Location = new global::System.Drawing.Point(45, 70);
			this.cmNote01Setup.Name = "cmNote01Setup";
			this.cmNote01Setup.Size = new global::System.Drawing.Size(50, 23);
			this.cmNote01Setup.TabIndex = 2;
			this.cmNote01Setup.Text = "Setup";
			this.cmNote01Setup.UseVisualStyleBackColor = false;
			this.Label11.AutoSize = true;
			this.Label11.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.Label11.Location = new global::System.Drawing.Point(5, 75);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(39, 13);
			this.Label11.TabIndex = 114;
			this.Label11.Text = "Note 1";
			this.cmNameSetup.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmNameSetup.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmNameSetup.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmNameSetup.ForeColor = global::System.Drawing.Color.Black;
			this.cmNameSetup.Location = new global::System.Drawing.Point(45, 45);
			this.cmNameSetup.Name = "cmNameSetup";
			this.cmNameSetup.Size = new global::System.Drawing.Size(50, 23);
			this.cmNameSetup.TabIndex = 1;
			this.cmNameSetup.Text = "Setup";
			this.cmNameSetup.UseVisualStyleBackColor = false;
			this.Label10.AutoSize = true;
			this.Label10.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.Label10.Location = new global::System.Drawing.Point(5, 50);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(35, 13);
			this.Label10.TabIndex = 111;
			this.Label10.Text = "Name";
			this.Label9.AutoSize = true;
			this.Label9.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.Label9.Location = new global::System.Drawing.Point(5, 25);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(33, 13);
			this.Label9.TabIndex = 110;
			this.Label9.Text = "Rank";
			this.cmRankSetup.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmRankSetup.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmRankSetup.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmRankSetup.ForeColor = global::System.Drawing.Color.Black;
			this.cmRankSetup.Location = new global::System.Drawing.Point(45, 20);
			this.cmRankSetup.Name = "cmRankSetup";
			this.cmRankSetup.Size = new global::System.Drawing.Size(50, 23);
			this.cmRankSetup.TabIndex = 0;
			this.cmRankSetup.Text = "Setup";
			this.cmRankSetup.UseVisualStyleBackColor = false;
			this.cmSave.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSave.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSave.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSave.ForeColor = global::System.Drawing.Color.Black;
			this.cmSave.Location = new global::System.Drawing.Point(880, 155);
			this.cmSave.Name = "cmSave";
			this.cmSave.Size = new global::System.Drawing.Size(105, 26);
			this.cmSave.TabIndex = 7;
			this.cmSave.Text = "Save Stats Image";
			this.cmSave.UseVisualStyleBackColor = false;
			this.gbLayout.Controls.Add(this.cmStatsModeHelp);
			this.gbLayout.Controls.Add(this.cmDefaults);
			this.gbLayout.Controls.Add(this.tbYSize);
			this.gbLayout.Controls.Add(this.tbXsize);
			this.gbLayout.Controls.Add(this.tbYoff);
			this.gbLayout.Controls.Add(this.tbXoff);
			this.gbLayout.Controls.Add(this.Label7);
			this.gbLayout.Controls.Add(this.cboNoteSpace);
			this.gbLayout.Controls.Add(this.Label5);
			this.gbLayout.Controls.Add(this.cmSizeRefresh);
			this.gbLayout.Controls.Add(this.cboLayoutX);
			this.gbLayout.Controls.Add(this.Label3);
			this.gbLayout.Controls.Add(this.Label6);
			this.gbLayout.Controls.Add(this.cboLayoutY);
			this.gbLayout.Controls.Add(this.Label4);
			this.gbLayout.Location = new global::System.Drawing.Point(335, 0);
			this.gbLayout.Name = "gbLayout";
			this.gbLayout.Size = new global::System.Drawing.Size(194, 185);
			this.gbLayout.TabIndex = 76;
			this.gbLayout.TabStop = false;
			this.gbLayout.Text = "Stats Layout";
			this.cmStatsModeHelp.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmStatsModeHelp.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmStatsModeHelp.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmStatsModeHelp.ForeColor = global::System.Drawing.Color.Black;
			this.cmStatsModeHelp.Location = new global::System.Drawing.Point(70, 145);
			this.cmStatsModeHelp.Name = "cmStatsModeHelp";
			this.cmStatsModeHelp.Size = new global::System.Drawing.Size(56, 26);
			this.cmStatsModeHelp.TabIndex = 26;
			this.cmStatsModeHelp.Text = "Help";
			this.cmStatsModeHelp.UseVisualStyleBackColor = false;
			this.cmDefaults.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmDefaults.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmDefaults.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmDefaults.ForeColor = global::System.Drawing.Color.Black;
			this.cmDefaults.Location = new global::System.Drawing.Point(10, 145);
			this.cmDefaults.Name = "cmDefaults";
			this.cmDefaults.Size = new global::System.Drawing.Size(58, 26);
			this.cmDefaults.TabIndex = 25;
			this.cmDefaults.Text = "Defaults";
			this.cmDefaults.UseVisualStyleBackColor = false;
			this.tbYSize.Location = new global::System.Drawing.Point(126, 15);
			this.tbYSize.Name = "tbYSize";
			this.tbYSize.Size = new global::System.Drawing.Size(60, 20);
			this.tbYSize.TabIndex = 19;
			this.tbXsize.Location = new global::System.Drawing.Point(60, 15);
			this.tbXsize.Name = "tbXsize";
			this.tbXsize.Size = new global::System.Drawing.Size(60, 20);
			this.tbXsize.TabIndex = 18;
			this.tbYoff.Location = new global::System.Drawing.Point(126, 40);
			this.tbYoff.Name = "tbYoff";
			this.tbYoff.Size = new global::System.Drawing.Size(60, 20);
			this.tbYoff.TabIndex = 21;
			this.tbXoff.Location = new global::System.Drawing.Point(60, 40);
			this.tbXoff.Name = "tbXoff";
			this.tbXoff.Size = new global::System.Drawing.Size(60, 20);
			this.tbXoff.TabIndex = 20;
			this.Label7.AutoSize = true;
			this.Label7.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.Label7.Location = new global::System.Drawing.Point(5, 45);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(52, 13);
			this.Label7.TabIndex = 77;
			this.Label7.Text = "XY Offset";
			this.cboNoteSpace.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cboNoteSpace.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboNoteSpace.ForeColor = global::System.Drawing.Color.White;
			this.cboNoteSpace.FormattingEnabled = true;
			this.cboNoteSpace.Location = new global::System.Drawing.Point(90, 115);
			this.cboNoteSpace.Name = "cboNoteSpace";
			this.cboNoteSpace.Size = new global::System.Drawing.Size(96, 21);
			this.cboNoteSpace.TabIndex = 24;
			this.Label5.AutoSize = true;
			this.Label5.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.Label5.Location = new global::System.Drawing.Point(5, 120);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(72, 13);
			this.Label5.TabIndex = 73;
			this.Label5.Text = "Note Spacing";
			this.cmSizeRefresh.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSizeRefresh.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSizeRefresh.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSizeRefresh.ForeColor = global::System.Drawing.Color.Black;
			this.cmSizeRefresh.Location = new global::System.Drawing.Point(128, 145);
			this.cmSizeRefresh.Name = "cmSizeRefresh";
			this.cmSizeRefresh.Size = new global::System.Drawing.Size(58, 26);
			this.cmSizeRefresh.TabIndex = 27;
			this.cmSizeRefresh.Text = "Refresh";
			this.cmSizeRefresh.UseVisualStyleBackColor = false;
			this.cboLayoutX.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cboLayoutX.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboLayoutX.ForeColor = global::System.Drawing.Color.White;
			this.cboLayoutX.FormattingEnabled = true;
			this.cboLayoutX.Location = new global::System.Drawing.Point(60, 65);
			this.cboLayoutX.Name = "cboLayoutX";
			this.cboLayoutX.Size = new global::System.Drawing.Size(126, 21);
			this.cboLayoutX.TabIndex = 22;
			this.Label6.AutoSize = true;
			this.Label6.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.Label6.Location = new global::System.Drawing.Point(5, 70);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(49, 13);
			this.Label6.TabIndex = 72;
			this.Label6.Text = "X Layout";
			this.cmGUIDark.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmGUIDark.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmGUIDark.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmGUIDark.ForeColor = global::System.Drawing.Color.Black;
			this.cmGUIDark.Location = new global::System.Drawing.Point(990, 125);
			this.cmGUIDark.Name = "cmGUIDark";
			this.cmGUIDark.Size = new global::System.Drawing.Size(125, 26);
			this.cmGUIDark.TabIndex = 8;
			this.cmGUIDark.Text = "set GUI to Dark";
			this.cmGUIDark.UseVisualStyleBackColor = false;
			this.cmGUILite.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmGUILite.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmGUILite.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmGUILite.ForeColor = global::System.Drawing.Color.Black;
			this.cmGUILite.Location = new global::System.Drawing.Point(990, 155);
			this.cmGUILite.Name = "cmGUILite";
			this.cmGUILite.Size = new global::System.Drawing.Size(125, 26);
			this.cmGUILite.TabIndex = 9;
			this.cmGUILite.Text = "Set GUI to Light";
			this.cmGUILite.UseVisualStyleBackColor = false;
			this.pbStats.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.pbStats.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.pbStats.Location = new global::System.Drawing.Point(10, 190);
			this.pbStats.Name = "pbStats";
			this.pbStats.Size = new global::System.Drawing.Size(1280, 320);
			this.pbStats.TabIndex = 77;
			this.pbStats.TabStop = false;
			this.cmTestData.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmTestData.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmTestData.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmTestData.ForeColor = global::System.Drawing.Color.Black;
			this.cmTestData.Location = new global::System.Drawing.Point(880, 95);
			this.cmTestData.Name = "cmTestData";
			this.cmTestData.Size = new global::System.Drawing.Size(105, 26);
			this.cmTestData.TabIndex = 5;
			this.cmTestData.Text = "Show Test Data";
			this.cmTestData.UseVisualStyleBackColor = false;
			this.cmLastMatch.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmLastMatch.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmLastMatch.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmLastMatch.ForeColor = global::System.Drawing.Color.Black;
			this.cmLastMatch.Location = new global::System.Drawing.Point(880, 65);
			this.cmLastMatch.Name = "cmLastMatch";
			this.cmLastMatch.Size = new global::System.Drawing.Size(105, 26);
			this.cmLastMatch.TabIndex = 4;
			this.cmLastMatch.Text = "Last Match Stats";
			this.cmLastMatch.UseVisualStyleBackColor = false;
			this.gbFX.Controls.Add(this.chkFX);
			this.gbFX.Controls.Add(this.Label1);
			this.gbFX.Controls.Add(this.cmFXModeHelp);
			this.gbFX.Controls.Add(this.cboFXVar1);
			this.gbFX.Controls.Add(this.lbFXVar1);
			this.gbFX.Controls.Add(this.cboFxVar3);
			this.gbFX.Controls.Add(this.lbFXVar3);
			this.gbFX.Controls.Add(this.cboFxVar4);
			this.gbFX.Controls.Add(this.cmFX3DC);
			this.gbFX.Controls.Add(this.cboFXVar2);
			this.gbFX.Controls.Add(this.lbFXVar2);
			this.gbFX.Controls.Add(this.lbFXVar4);
			this.gbFX.Location = new global::System.Drawing.Point(535, 0);
			this.gbFX.Name = "gbFX";
			this.gbFX.Size = new global::System.Drawing.Size(145, 185);
			this.gbFX.TabIndex = 80;
			this.gbFX.TabStop = false;
			this.gbFX.Text = "Stats FX";
			this.chkFX.AutoSize = true;
			this.chkFX.Enabled = false;
			this.chkFX.Location = new global::System.Drawing.Point(66, 42);
			this.chkFX.Name = "chkFX";
			this.chkFX.Size = new global::System.Drawing.Size(56, 17);
			this.chkFX.TabIndex = 88;
			this.chkFX.Text = "Active";
			this.chkFX.UseVisualStyleBackColor = true;
			this.Label1.AutoSize = true;
			this.Label1.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.Label1.Location = new global::System.Drawing.Point(6, 45);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(34, 13);
			this.Label1.TabIndex = 89;
			this.Label1.Text = "Mode";
			this.cmFXModeHelp.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmFXModeHelp.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmFXModeHelp.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmFXModeHelp.ForeColor = global::System.Drawing.Color.Black;
			this.cmFXModeHelp.Location = new global::System.Drawing.Point(65, 145);
			this.cmFXModeHelp.Name = "cmFXModeHelp";
			this.cmFXModeHelp.Size = new global::System.Drawing.Size(71, 26);
			this.cmFXModeHelp.TabIndex = 93;
			this.cmFXModeHelp.Text = "Help";
			this.cmFXModeHelp.UseVisualStyleBackColor = false;
			this.cboFXVar1.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cboFXVar1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboFXVar1.ForeColor = global::System.Drawing.Color.White;
			this.cboFXVar1.FormattingEnabled = true;
			this.cboFXVar1.Location = new global::System.Drawing.Point(65, 15);
			this.cboFXVar1.Name = "cboFXVar1";
			this.cboFXVar1.Size = new global::System.Drawing.Size(71, 21);
			this.cboFXVar1.TabIndex = 87;
			this.lbFXVar1.AutoSize = true;
			this.lbFXVar1.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.lbFXVar1.Location = new global::System.Drawing.Point(6, 21);
			this.lbFXVar1.Name = "lbFXVar1";
			this.lbFXVar1.Size = new global::System.Drawing.Size(34, 13);
			this.lbFXVar1.TabIndex = 86;
			this.lbFXVar1.Text = "Mode";
			this.cboFxVar3.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cboFxVar3.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboFxVar3.Enabled = false;
			this.cboFxVar3.ForeColor = global::System.Drawing.Color.White;
			this.cboFxVar3.FormattingEnabled = true;
			this.cboFxVar3.Location = new global::System.Drawing.Point(65, 89);
			this.cboFxVar3.Name = "cboFxVar3";
			this.cboFxVar3.Size = new global::System.Drawing.Size(71, 21);
			this.cboFxVar3.TabIndex = 91;
			this.lbFXVar3.AutoSize = true;
			this.lbFXVar3.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.lbFXVar3.Location = new global::System.Drawing.Point(6, 91);
			this.lbFXVar3.Name = "lbFXVar3";
			this.lbFXVar3.Size = new global::System.Drawing.Size(13, 13);
			this.lbFXVar3.TabIndex = 84;
			this.lbFXVar3.Text = "--";
			this.cboFxVar4.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cboFxVar4.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboFxVar4.Enabled = false;
			this.cboFxVar4.ForeColor = global::System.Drawing.Color.White;
			this.cboFxVar4.FormattingEnabled = true;
			this.cboFxVar4.Location = new global::System.Drawing.Point(65, 113);
			this.cboFxVar4.Name = "cboFxVar4";
			this.cboFxVar4.Size = new global::System.Drawing.Size(71, 21);
			this.cboFxVar4.TabIndex = 92;
			this.cmFX3DC.Enabled = false;
			this.cmFX3DC.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmFX3DC.Location = new global::System.Drawing.Point(65, 65);
			this.cmFX3DC.Name = "cmFX3DC";
			this.cmFX3DC.Size = new global::System.Drawing.Size(21, 21);
			this.cmFX3DC.TabIndex = 89;
			this.cmFX3DC.Text = "1";
			this.cmFX3DC.UseVisualStyleBackColor = true;
			this.cboFXVar2.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cboFXVar2.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboFXVar2.Enabled = false;
			this.cboFXVar2.ForeColor = global::System.Drawing.Color.White;
			this.cboFXVar2.FormattingEnabled = true;
			this.cboFXVar2.Location = new global::System.Drawing.Point(90, 65);
			this.cboFXVar2.Name = "cboFXVar2";
			this.cboFXVar2.Size = new global::System.Drawing.Size(46, 21);
			this.cboFXVar2.TabIndex = 90;
			this.lbFXVar2.AutoSize = true;
			this.lbFXVar2.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.lbFXVar2.Location = new global::System.Drawing.Point(6, 68);
			this.lbFXVar2.Name = "lbFXVar2";
			this.lbFXVar2.Size = new global::System.Drawing.Size(13, 13);
			this.lbFXVar2.TabIndex = 66;
			this.lbFXVar2.Text = "--";
			this.lbFXVar4.AutoSize = true;
			this.lbFXVar4.ForeColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.lbFXVar4.Location = new global::System.Drawing.Point(6, 115);
			this.lbFXVar4.Name = "lbFXVar4";
			this.lbFXVar4.Size = new global::System.Drawing.Size(13, 13);
			this.lbFXVar4.TabIndex = 70;
			this.lbFXVar4.Text = "--";
			this.lbError1.BackColor = global::System.Drawing.Color.Silver;
			this.lbError1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.lbError1.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lbError1.ForeColor = global::System.Drawing.Color.White;
			this.lbError1.Location = new global::System.Drawing.Point(10, 70);
			this.lbError1.Name = "lbError1";
			this.lbError1.Size = new global::System.Drawing.Size(111, 18);
			this.lbError1.TabIndex = 81;
			this.lbError1.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.lbError2.BackColor = global::System.Drawing.Color.Silver;
			this.lbError2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.lbError2.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lbError2.ForeColor = global::System.Drawing.Color.White;
			this.lbError2.Location = new global::System.Drawing.Point(10, 90);
			this.lbError2.Name = "lbError2";
			this.lbError2.Size = new global::System.Drawing.Size(111, 18);
			this.lbError2.TabIndex = 82;
			this.lbError2.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.chkMismatch.AutoSize = true;
			this.chkMismatch.Location = new global::System.Drawing.Point(990, 52);
			this.chkMismatch.Name = "chkMismatch";
			this.chkMismatch.Size = new global::System.Drawing.Size(102, 17);
			this.chkMismatch.TabIndex = 11;
			this.chkMismatch.Text = "Show Bad Stats";
			this.chkMismatch.UseVisualStyleBackColor = true;
			this.chkTips.AutoSize = true;
			this.chkTips.Location = new global::System.Drawing.Point(990, 35);
			this.chkTips.Name = "chkTips";
			this.chkTips.Size = new global::System.Drawing.Size(100, 17);
			this.chkTips.TabIndex = 10;
			this.chkTips.Text = "Show Tool Tips";
			this.chkTips.UseVisualStyleBackColor = true;
			this.pbNote1.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.pbNote1.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.pbNote1.Location = new global::System.Drawing.Point(10, 515);
			this.pbNote1.Name = "pbNote1";
			this.pbNote1.Size = new global::System.Drawing.Size(500, 60);
			this.pbNote1.TabIndex = 91;
			this.pbNote1.TabStop = false;
			this.timNote1.Enabled = true;
			this.timNote1.Interval = 30;
			this.gbSound.Controls.Add(this.cmAudioStop);
			this.gbSound.Controls.Add(this.lbVolume);
			this.gbSound.Controls.Add(this.scrVolume);
			this.gbSound.Controls.Add(this.cmSound15);
			this.gbSound.Controls.Add(this.cmSound14);
			this.gbSound.Controls.Add(this.cmSound13);
			this.gbSound.Controls.Add(this.cmSound12);
			this.gbSound.Controls.Add(this.cmSound11);
			this.gbSound.Controls.Add(this.lbSoundCurrent);
			this.gbSound.Controls.Add(this.cmSound10);
			this.gbSound.Controls.Add(this.cmSound09);
			this.gbSound.Controls.Add(this.cmSound08);
			this.gbSound.Controls.Add(this.cmSound07);
			this.gbSound.Controls.Add(this.cmSound06);
			this.gbSound.Controls.Add(this.cmSound05);
			this.gbSound.Controls.Add(this.cmSound04);
			this.gbSound.Controls.Add(this.cmSound03);
			this.gbSound.Controls.Add(this.cmSound02);
			this.gbSound.Controls.Add(this.cmSound01);
			this.gbSound.Location = new global::System.Drawing.Point(685, 0);
			this.gbSound.Name = "gbSound";
			this.gbSound.Size = new global::System.Drawing.Size(190, 185);
			this.gbSound.TabIndex = 94;
			this.gbSound.TabStop = false;
			this.gbSound.Text = "Sound";
			this.cmAudioStop.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmAudioStop.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmAudioStop.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmAudioStop.ForeColor = global::System.Drawing.Color.Black;
			this.cmAudioStop.Location = new global::System.Drawing.Point(145, 160);
			this.cmAudioStop.Name = "cmAudioStop";
			this.cmAudioStop.Size = new global::System.Drawing.Size(35, 18);
			this.cmAudioStop.TabIndex = 34;
			this.cmAudioStop.Text = "▀";
			this.cmAudioStop.UseVisualStyleBackColor = false;
			this.lbVolume.BackColor = global::System.Drawing.Color.Silver;
			this.lbVolume.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.lbVolume.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lbVolume.ForeColor = global::System.Drawing.Color.Black;
			this.lbVolume.Location = new global::System.Drawing.Point(105, 160);
			this.lbVolume.Name = "lbVolume";
			this.lbVolume.Size = new global::System.Drawing.Size(35, 18);
			this.lbVolume.TabIndex = 33;
			this.lbVolume.Text = "100";
			this.lbVolume.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.scrVolume.Location = new global::System.Drawing.Point(5, 160);
			this.scrVolume.Maximum = 109;
			this.scrVolume.Name = "scrVolume";
			this.scrVolume.Size = new global::System.Drawing.Size(95, 18);
			this.scrVolume.TabIndex = 32;
			this.scrVolume.TabStop = true;
			this.scrVolume.Value = 100;
			this.cmSound15.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSound15.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSound15.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSound15.ForeColor = global::System.Drawing.Color.Black;
			this.cmSound15.Location = new global::System.Drawing.Point(125, 115);
			this.cmSound15.Name = "cmSound15";
			this.cmSound15.Size = new global::System.Drawing.Size(55, 23);
			this.cmSound15.TabIndex = 31;
			this.cmSound15.Text = "> 15";
			this.cmSound15.UseVisualStyleBackColor = false;
			this.cmSound14.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSound14.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSound14.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSound14.ForeColor = global::System.Drawing.Color.Black;
			this.cmSound14.Location = new global::System.Drawing.Point(65, 115);
			this.cmSound14.Name = "cmSound14";
			this.cmSound14.Size = new global::System.Drawing.Size(55, 23);
			this.cmSound14.TabIndex = 30;
			this.cmSound14.Text = "> 14";
			this.cmSound14.UseVisualStyleBackColor = false;
			this.cmSound13.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSound13.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSound13.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSound13.ForeColor = global::System.Drawing.Color.Black;
			this.cmSound13.Location = new global::System.Drawing.Point(5, 115);
			this.cmSound13.Name = "cmSound13";
			this.cmSound13.Size = new global::System.Drawing.Size(55, 23);
			this.cmSound13.TabIndex = 29;
			this.cmSound13.Text = "> 13";
			this.cmSound13.UseVisualStyleBackColor = false;
			this.cmSound12.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSound12.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSound12.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSound12.ForeColor = global::System.Drawing.Color.Black;
			this.cmSound12.Location = new global::System.Drawing.Point(125, 90);
			this.cmSound12.Name = "cmSound12";
			this.cmSound12.Size = new global::System.Drawing.Size(55, 23);
			this.cmSound12.TabIndex = 28;
			this.cmSound12.Text = "> 12";
			this.cmSound12.UseVisualStyleBackColor = false;
			this.cmSound11.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSound11.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSound11.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSound11.ForeColor = global::System.Drawing.Color.Black;
			this.cmSound11.Location = new global::System.Drawing.Point(65, 90);
			this.cmSound11.Name = "cmSound11";
			this.cmSound11.Size = new global::System.Drawing.Size(55, 23);
			this.cmSound11.TabIndex = 27;
			this.cmSound11.Text = "> 11";
			this.cmSound11.UseVisualStyleBackColor = false;
			this.lbSoundCurrent.BackColor = global::System.Drawing.Color.Silver;
			this.lbSoundCurrent.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.lbSoundCurrent.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lbSoundCurrent.ForeColor = global::System.Drawing.Color.Black;
			this.lbSoundCurrent.Location = new global::System.Drawing.Point(5, 140);
			this.lbSoundCurrent.Name = "lbSoundCurrent";
			this.lbSoundCurrent.Size = new global::System.Drawing.Size(175, 18);
			this.lbSoundCurrent.TabIndex = 26;
			this.lbSoundCurrent.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.cmSound10.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSound10.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSound10.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSound10.ForeColor = global::System.Drawing.Color.Black;
			this.cmSound10.Location = new global::System.Drawing.Point(5, 90);
			this.cmSound10.Name = "cmSound10";
			this.cmSound10.Size = new global::System.Drawing.Size(55, 23);
			this.cmSound10.TabIndex = 17;
			this.cmSound10.Text = "> 10";
			this.cmSound10.UseVisualStyleBackColor = false;
			this.cmSound09.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSound09.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSound09.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSound09.ForeColor = global::System.Drawing.Color.Black;
			this.cmSound09.Location = new global::System.Drawing.Point(125, 65);
			this.cmSound09.Name = "cmSound09";
			this.cmSound09.Size = new global::System.Drawing.Size(55, 23);
			this.cmSound09.TabIndex = 16;
			this.cmSound09.Text = "> 09";
			this.cmSound09.UseVisualStyleBackColor = false;
			this.cmSound08.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSound08.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSound08.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSound08.ForeColor = global::System.Drawing.Color.Black;
			this.cmSound08.Location = new global::System.Drawing.Point(65, 65);
			this.cmSound08.Name = "cmSound08";
			this.cmSound08.Size = new global::System.Drawing.Size(55, 23);
			this.cmSound08.TabIndex = 15;
			this.cmSound08.Text = "> 08";
			this.cmSound08.UseVisualStyleBackColor = false;
			this.cmSound07.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSound07.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSound07.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSound07.ForeColor = global::System.Drawing.Color.Black;
			this.cmSound07.Location = new global::System.Drawing.Point(5, 65);
			this.cmSound07.Name = "cmSound07";
			this.cmSound07.Size = new global::System.Drawing.Size(55, 23);
			this.cmSound07.TabIndex = 14;
			this.cmSound07.Text = "> 07";
			this.cmSound07.UseVisualStyleBackColor = false;
			this.cmSound06.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSound06.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSound06.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSound06.ForeColor = global::System.Drawing.Color.Black;
			this.cmSound06.Location = new global::System.Drawing.Point(125, 40);
			this.cmSound06.Name = "cmSound06";
			this.cmSound06.Size = new global::System.Drawing.Size(55, 23);
			this.cmSound06.TabIndex = 13;
			this.cmSound06.Text = "> 06";
			this.cmSound06.UseVisualStyleBackColor = false;
			this.cmSound05.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSound05.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSound05.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSound05.ForeColor = global::System.Drawing.Color.Black;
			this.cmSound05.Location = new global::System.Drawing.Point(65, 40);
			this.cmSound05.Name = "cmSound05";
			this.cmSound05.Size = new global::System.Drawing.Size(55, 23);
			this.cmSound05.TabIndex = 12;
			this.cmSound05.Text = "> 05";
			this.cmSound05.UseVisualStyleBackColor = false;
			this.cmSound04.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSound04.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSound04.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSound04.ForeColor = global::System.Drawing.Color.Black;
			this.cmSound04.Location = new global::System.Drawing.Point(5, 40);
			this.cmSound04.Name = "cmSound04";
			this.cmSound04.Size = new global::System.Drawing.Size(55, 23);
			this.cmSound04.TabIndex = 11;
			this.cmSound04.Text = "> 04";
			this.cmSound04.UseVisualStyleBackColor = false;
			this.cmSound03.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSound03.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSound03.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSound03.ForeColor = global::System.Drawing.Color.Black;
			this.cmSound03.Location = new global::System.Drawing.Point(125, 15);
			this.cmSound03.Name = "cmSound03";
			this.cmSound03.Size = new global::System.Drawing.Size(55, 23);
			this.cmSound03.TabIndex = 10;
			this.cmSound03.Text = "> 03";
			this.cmSound03.UseVisualStyleBackColor = false;
			this.cmSound02.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSound02.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSound02.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSound02.ForeColor = global::System.Drawing.Color.Black;
			this.cmSound02.Location = new global::System.Drawing.Point(65, 15);
			this.cmSound02.Name = "cmSound02";
			this.cmSound02.Size = new global::System.Drawing.Size(55, 23);
			this.cmSound02.TabIndex = 9;
			this.cmSound02.Text = "> 02";
			this.cmSound02.UseVisualStyleBackColor = false;
			this.cmSound01.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 232);
			this.cmSound01.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(232, 255, 232);
			this.cmSound01.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmSound01.ForeColor = global::System.Drawing.Color.Black;
			this.cmSound01.Location = new global::System.Drawing.Point(5, 15);
			this.cmSound01.Name = "cmSound01";
			this.cmSound01.Size = new global::System.Drawing.Size(55, 23);
			this.cmSound01.TabIndex = 8;
			this.cmSound01.Text = "> 01";
			this.cmSound01.UseVisualStyleBackColor = false;
			this.pbNote3.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.pbNote3.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.pbNote3.Location = new global::System.Drawing.Point(10, 645);
			this.pbNote3.Name = "pbNote3";
			this.pbNote3.Size = new global::System.Drawing.Size(500, 60);
			this.pbNote3.TabIndex = 96;
			this.pbNote3.TabStop = false;
			this.pbNote4.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.pbNote4.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.pbNote4.Location = new global::System.Drawing.Point(10, 710);
			this.pbNote4.Name = "pbNote4";
			this.pbNote4.Size = new global::System.Drawing.Size(500, 60);
			this.pbNote4.TabIndex = 97;
			this.pbNote4.TabStop = false;
			this.pbNote2.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.pbNote2.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.pbNote2.Location = new global::System.Drawing.Point(10, 580);
			this.pbNote2.Name = "pbNote2";
			this.pbNote2.Size = new global::System.Drawing.Size(500, 60);
			this.pbNote2.TabIndex = 98;
			this.pbNote2.TabStop = false;
			this.chkPosition.AutoSize = true;
			this.chkPosition.Location = new global::System.Drawing.Point(990, 69);
			this.chkPosition.Name = "chkPosition";
			this.chkPosition.Size = new global::System.Drawing.Size(133, 17);
			this.chkPosition.TabIndex = 12;
			this.chkPosition.Text = "Save Window Position";
			this.chkPosition.UseVisualStyleBackColor = true;
			this.tsmPlayer.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.tsmPlayer_Relic,
				this.tsmPlayer_OrgAT,
				this.tsmPlayer_OrgFaction,
				this.tsmPlayer_OrgPlayercard,
				this.tsmPlayer_Google
			});
			this.tsmPlayer.Name = "tsmPlayer";
			this.tsmPlayer.Size = new global::System.Drawing.Size(290, 114);
			this.tsmPlayer_Relic.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("tsmPlayer_Relic.Image");
			this.tsmPlayer_Relic.Name = "tsmPlayer_Relic";
			this.tsmPlayer_Relic.Size = new global::System.Drawing.Size(289, 22);
			this.tsmPlayer_Relic.Text = "&1 - Open Relic Stats webpage";
			this.tsmPlayer_OrgAT.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("tsmPlayer_OrgAT.Image");
			this.tsmPlayer_OrgAT.Name = "tsmPlayer_OrgAT";
			this.tsmPlayer_OrgAT.Size = new global::System.Drawing.Size(289, 22);
			this.tsmPlayer_OrgAT.Text = "&2 - Open Coh2.Org AT stats webpage";
			this.tsmPlayer_OrgFaction.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("tsmPlayer_OrgFaction.Image");
			this.tsmPlayer_OrgFaction.Name = "tsmPlayer_OrgFaction";
			this.tsmPlayer_OrgFaction.Size = new global::System.Drawing.Size(289, 22);
			this.tsmPlayer_OrgFaction.Text = "3 - Open Coh2.Org Faction webpage";
			this.tsmPlayer_OrgPlayercard.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("tsmPlayer_OrgPlayercard.Image");
			this.tsmPlayer_OrgPlayercard.Name = "tsmPlayer_OrgPlayercard";
			this.tsmPlayer_OrgPlayercard.Size = new global::System.Drawing.Size(289, 22);
			this.tsmPlayer_OrgPlayercard.Text = "&4 - Open Coh2.Org Playercard webpage";
			this.tsmPlayer_Google.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("tsmPlayer_Google.Image");
			this.tsmPlayer_Google.Name = "tsmPlayer_Google";
			this.tsmPlayer_Google.Size = new global::System.Drawing.Size(289, 22);
			this.tsmPlayer_Google.Text = "&5 - Send player name to Google Translate";
			this.chkPopUp.AutoSize = true;
			this.chkPopUp.Location = new global::System.Drawing.Point(990, 86);
			this.chkPopUp.Name = "chkPopUp";
			this.chkPopUp.Size = new global::System.Drawing.Size(106, 17);
			this.chkPopUp.TabIndex = 13;
			this.chkPopUp.Text = "Use Stats Popup";
			this.chkPopUp.UseVisualStyleBackColor = true;
			this.tsmAudio.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.tsmSetVolTo100,
				this.tsmSetVolTo90,
				this.tsmSetVolTo80,
				this.tsmSetVolTo70,
				this.tsmSetVolTo60,
				this.tsmSetVolTo50,
				this.tsmSetVolTo40,
				this.tsmSetVolTo30,
				this.tsmSetVolTo20,
				this.tsmSetVolTo10,
				this.ToolStripMenuItem1,
				this.tsmSelectFile
			});
			this.tsmAudio.Name = "tsmAudio";
			this.tsmAudio.Size = new global::System.Drawing.Size(216, 252);
			this.tsmSetVolTo100.Name = "tsmSetVolTo100";
			this.tsmSetVolTo100.Size = new global::System.Drawing.Size(215, 22);
			this.tsmSetVolTo100.Text = "&0 - Set Vol to 100%";
			this.tsmSetVolTo90.Name = "tsmSetVolTo90";
			this.tsmSetVolTo90.Size = new global::System.Drawing.Size(215, 22);
			this.tsmSetVolTo90.Text = "9 - Set Vol to 90%";
			this.tsmSetVolTo80.Name = "tsmSetVolTo80";
			this.tsmSetVolTo80.Size = new global::System.Drawing.Size(215, 22);
			this.tsmSetVolTo80.Text = "8 - Set Vol to 80%";
			this.tsmSetVolTo70.Name = "tsmSetVolTo70";
			this.tsmSetVolTo70.Size = new global::System.Drawing.Size(215, 22);
			this.tsmSetVolTo70.Text = "7 - Set Vol to 70%";
			this.tsmSetVolTo60.Name = "tsmSetVolTo60";
			this.tsmSetVolTo60.Size = new global::System.Drawing.Size(215, 22);
			this.tsmSetVolTo60.Text = "6 - Set Vol to 60%";
			this.tsmSetVolTo50.Name = "tsmSetVolTo50";
			this.tsmSetVolTo50.Size = new global::System.Drawing.Size(215, 22);
			this.tsmSetVolTo50.Text = "5 - Set Vol to 50%";
			this.tsmSetVolTo40.Name = "tsmSetVolTo40";
			this.tsmSetVolTo40.Size = new global::System.Drawing.Size(215, 22);
			this.tsmSetVolTo40.Text = "4 - Set Vol to 40%";
			this.tsmSetVolTo30.Name = "tsmSetVolTo30";
			this.tsmSetVolTo30.Size = new global::System.Drawing.Size(215, 22);
			this.tsmSetVolTo30.Text = "3 - Set Vol to 30%";
			this.tsmSetVolTo20.Name = "tsmSetVolTo20";
			this.tsmSetVolTo20.Size = new global::System.Drawing.Size(215, 22);
			this.tsmSetVolTo20.Text = "2 - Set Vol to 20%";
			this.tsmSetVolTo10.Name = "tsmSetVolTo10";
			this.tsmSetVolTo10.Size = new global::System.Drawing.Size(215, 22);
			this.tsmSetVolTo10.Text = "1 - Set Vol to 10%";
			this.ToolStripMenuItem1.Name = "ToolStripMenuItem1";
			this.ToolStripMenuItem1.Size = new global::System.Drawing.Size(212, 6);
			this.tsmSelectFile.Name = "tsmSelectFile";
			this.tsmSelectFile.Size = new global::System.Drawing.Size(215, 22);
			this.tsmSelectFile.Text = "F - Select Audio file to play";
			this.chkSmoothAni.AutoSize = true;
			this.chkSmoothAni.Location = new global::System.Drawing.Point(990, 104);
			this.chkSmoothAni.Name = "chkSmoothAni";
			this.chkSmoothAni.Size = new global::System.Drawing.Size(111, 17);
			this.chkSmoothAni.TabIndex = 14;
			this.chkSmoothAni.Text = "Smooth Animation";
			this.chkSmoothAni.UseVisualStyleBackColor = true;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.FromArgb(232, 232, 242);
			base.ClientSize = new global::System.Drawing.Size(1302, 782);
			base.Controls.Add(this.chkSmoothAni);
			base.Controls.Add(this.chkPopUp);
			base.Controls.Add(this.chkPosition);
			base.Controls.Add(this.cmCopy);
			base.Controls.Add(this.cmSave);
			base.Controls.Add(this.pbNote2);
			base.Controls.Add(this.pbNote4);
			base.Controls.Add(this.pbNote3);
			base.Controls.Add(this.gbSound);
			base.Controls.Add(this.cmGUIDark);
			base.Controls.Add(this.cmGUILite);
			base.Controls.Add(this.pbNote1);
			base.Controls.Add(this.chkTips);
			base.Controls.Add(this.chkMismatch);
			base.Controls.Add(this.lbError2);
			base.Controls.Add(this.lbError1);
			base.Controls.Add(this.gbFX);
			base.Controls.Add(this.cmLastMatch);
			base.Controls.Add(this.cmTestData);
			base.Controls.Add(this.pbStats);
			base.Controls.Add(this.gbLayout);
			base.Controls.Add(this.gbRank);
			base.Controls.Add(this.cmAbout);
			base.Controls.Add(this.Label2);
			base.Controls.Add(this.cmScanLog);
			base.Controls.Add(this.cmFindLog);
			base.Controls.Add(this.lbSteam08);
			base.Controls.Add(this.lbSteam07);
			base.Controls.Add(this.lbSteam06);
			base.Controls.Add(this.lbSteam05);
			base.Controls.Add(this.lbSteam04);
			base.Controls.Add(this.lbSteam03);
			base.Controls.Add(this.lbSteam02);
			base.Controls.Add(this.lbSteam01);
			base.Controls.Add(this.pbFact05);
			base.Controls.Add(this.pbFact04);
			base.Controls.Add(this.pbFact03);
			base.Controls.Add(this.pbFact02);
			base.Controls.Add(this.pbFact01);
			base.Controls.Add(this.lbStatus);
			base.Controls.Add(this.cmCheckLog);
			this.DoubleBuffered = true;
			this.ForeColor = global::System.Drawing.Color.Black;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "frmMain";
			this.Text = "MakoCelo v4.10";
			((global::System.ComponentModel.ISupportInitialize)this.pbFact01).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.pbFact02).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.pbFact03).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.pbFact04).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.pbFact05).EndInit();
			this.gbRank.ResumeLayout(false);
			this.gbRank.PerformLayout();
			this.gbLayout.ResumeLayout(false);
			this.gbLayout.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.pbStats).EndInit();
			this.gbFX.ResumeLayout(false);
			this.gbFX.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.pbNote1).EndInit();
			this.gbSound.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.pbNote3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.pbNote4).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.pbNote2).EndInit();
			this.tsmPlayer.ResumeLayout(false);
			this.tsmAudio.ResumeLayout(false);
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x04000115 RID: 277
		private global::System.ComponentModel.IContainer components;
	}
}
