namespace MakoCelo
{
	// Token: 0x0200000A RID: 10
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmNotes : global::System.Windows.Forms.Form
	{
		// Token: 0x060000A4 RID: 164 RVA: 0x00006D7C File Offset: 0x00004F7C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060000A5 RID: 165 RVA: 0x00006DBC File Offset: 0x00004FBC
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::MakoCelo.frmNotes));
			this.tbN04 = new global::System.Windows.Forms.TextBox();
			this.tbN03 = new global::System.Windows.Forms.TextBox();
			this.tbN02 = new global::System.Windows.Forms.TextBox();
			this.tbN01 = new global::System.Windows.Forms.TextBox();
			this.tbN05 = new global::System.Windows.Forms.TextBox();
			this.tbN10 = new global::System.Windows.Forms.TextBox();
			this.tbN09 = new global::System.Windows.Forms.TextBox();
			this.tbN08 = new global::System.Windows.Forms.TextBox();
			this.tbN07 = new global::System.Windows.Forms.TextBox();
			this.tbN06 = new global::System.Windows.Forms.TextBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.Button6 = new global::System.Windows.Forms.Button();
			this.Button7 = new global::System.Windows.Forms.Button();
			this.Button8 = new global::System.Windows.Forms.Button();
			this.Button9 = new global::System.Windows.Forms.Button();
			this.Button10 = new global::System.Windows.Forms.Button();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.cmOK = new global::System.Windows.Forms.Button();
			this.cmCancel = new global::System.Windows.Forms.Button();
			this.cboMode = new global::System.Windows.Forms.ComboBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.cboSpeed = new global::System.Windows.Forms.ComboBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.cboHoldTime = new global::System.Windows.Forms.ComboBox();
			this.tbDelim = new global::System.Windows.Forms.TextBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.cboAlign = new global::System.Windows.Forms.ComboBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.lbXOff = new global::System.Windows.Forms.Label();
			this.tbXoff = new global::System.Windows.Forms.TextBox();
			this.lbYoff = new global::System.Windows.Forms.Label();
			this.tbYoff = new global::System.Windows.Forms.TextBox();
			this.Button11 = new global::System.Windows.Forms.Button();
			this.Button12 = new global::System.Windows.Forms.Button();
			this.Button13 = new global::System.Windows.Forms.Button();
			this.ToolTip1 = new global::System.Windows.Forms.ToolTip(this.components);
			base.SuspendLayout();
			this.tbN04.BackColor = global::System.Drawing.Color.White;
			this.tbN04.ForeColor = global::System.Drawing.Color.Black;
			this.tbN04.Location = new global::System.Drawing.Point(15, 105);
			this.tbN04.Name = "tbN04";
			this.tbN04.Size = new global::System.Drawing.Size(467, 20);
			this.tbN04.TabIndex = 4;
			this.tbN03.BackColor = global::System.Drawing.Color.White;
			this.tbN03.ForeColor = global::System.Drawing.Color.Black;
			this.tbN03.Location = new global::System.Drawing.Point(15, 80);
			this.tbN03.Name = "tbN03";
			this.tbN03.Size = new global::System.Drawing.Size(467, 20);
			this.tbN03.TabIndex = 3;
			this.tbN02.BackColor = global::System.Drawing.Color.White;
			this.tbN02.ForeColor = global::System.Drawing.Color.Black;
			this.tbN02.Location = new global::System.Drawing.Point(15, 55);
			this.tbN02.Name = "tbN02";
			this.tbN02.Size = new global::System.Drawing.Size(467, 20);
			this.tbN02.TabIndex = 2;
			this.tbN01.BackColor = global::System.Drawing.Color.White;
			this.tbN01.ForeColor = global::System.Drawing.Color.Black;
			this.tbN01.Location = new global::System.Drawing.Point(15, 30);
			this.tbN01.Name = "tbN01";
			this.tbN01.Size = new global::System.Drawing.Size(467, 20);
			this.tbN01.TabIndex = 1;
			this.tbN05.BackColor = global::System.Drawing.Color.White;
			this.tbN05.ForeColor = global::System.Drawing.Color.Black;
			this.tbN05.Location = new global::System.Drawing.Point(15, 130);
			this.tbN05.Name = "tbN05";
			this.tbN05.Size = new global::System.Drawing.Size(467, 20);
			this.tbN05.TabIndex = 5;
			this.tbN10.BackColor = global::System.Drawing.Color.White;
			this.tbN10.ForeColor = global::System.Drawing.Color.Black;
			this.tbN10.Location = new global::System.Drawing.Point(15, 255);
			this.tbN10.Name = "tbN10";
			this.tbN10.Size = new global::System.Drawing.Size(467, 20);
			this.tbN10.TabIndex = 10;
			this.tbN09.BackColor = global::System.Drawing.Color.White;
			this.tbN09.ForeColor = global::System.Drawing.Color.Black;
			this.tbN09.Location = new global::System.Drawing.Point(15, 230);
			this.tbN09.Name = "tbN09";
			this.tbN09.Size = new global::System.Drawing.Size(467, 20);
			this.tbN09.TabIndex = 9;
			this.tbN08.BackColor = global::System.Drawing.Color.White;
			this.tbN08.ForeColor = global::System.Drawing.Color.Black;
			this.tbN08.Location = new global::System.Drawing.Point(15, 205);
			this.tbN08.Name = "tbN08";
			this.tbN08.Size = new global::System.Drawing.Size(467, 20);
			this.tbN08.TabIndex = 8;
			this.tbN07.BackColor = global::System.Drawing.Color.White;
			this.tbN07.ForeColor = global::System.Drawing.Color.Black;
			this.tbN07.Location = new global::System.Drawing.Point(15, 180);
			this.tbN07.Name = "tbN07";
			this.tbN07.Size = new global::System.Drawing.Size(467, 20);
			this.tbN07.TabIndex = 7;
			this.tbN06.BackColor = global::System.Drawing.Color.White;
			this.tbN06.ForeColor = global::System.Drawing.Color.Black;
			this.tbN06.Location = new global::System.Drawing.Point(15, 155);
			this.tbN06.Name = "tbN06";
			this.tbN06.Size = new global::System.Drawing.Size(467, 20);
			this.tbN06.TabIndex = 6;
			this.Button1.Location = new global::System.Drawing.Point(485, 30);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(32, 20);
			this.Button1.TabIndex = 18;
			this.Button1.Text = "Clr";
			this.Button1.UseVisualStyleBackColor = true;
			this.Button2.Location = new global::System.Drawing.Point(485, 55);
			this.Button2.Name = "Button2";
			this.Button2.Size = new global::System.Drawing.Size(32, 20);
			this.Button2.TabIndex = 19;
			this.Button2.Text = "Clr";
			this.Button2.UseVisualStyleBackColor = true;
			this.Button3.Location = new global::System.Drawing.Point(485, 80);
			this.Button3.Name = "Button3";
			this.Button3.Size = new global::System.Drawing.Size(32, 20);
			this.Button3.TabIndex = 20;
			this.Button3.Text = "Clr";
			this.Button3.UseVisualStyleBackColor = true;
			this.Button4.Location = new global::System.Drawing.Point(485, 105);
			this.Button4.Name = "Button4";
			this.Button4.Size = new global::System.Drawing.Size(32, 20);
			this.Button4.TabIndex = 21;
			this.Button4.Text = "Clr";
			this.Button4.UseVisualStyleBackColor = true;
			this.Button5.Location = new global::System.Drawing.Point(485, 130);
			this.Button5.Name = "Button5";
			this.Button5.Size = new global::System.Drawing.Size(32, 20);
			this.Button5.TabIndex = 22;
			this.Button5.Text = "Clr";
			this.Button5.UseVisualStyleBackColor = true;
			this.Button6.Location = new global::System.Drawing.Point(485, 155);
			this.Button6.Name = "Button6";
			this.Button6.Size = new global::System.Drawing.Size(32, 20);
			this.Button6.TabIndex = 23;
			this.Button6.Text = "Clr";
			this.Button6.UseVisualStyleBackColor = true;
			this.Button7.Location = new global::System.Drawing.Point(485, 180);
			this.Button7.Name = "Button7";
			this.Button7.Size = new global::System.Drawing.Size(32, 20);
			this.Button7.TabIndex = 24;
			this.Button7.Text = "Clr";
			this.Button7.UseVisualStyleBackColor = true;
			this.Button8.Location = new global::System.Drawing.Point(485, 205);
			this.Button8.Name = "Button8";
			this.Button8.Size = new global::System.Drawing.Size(32, 20);
			this.Button8.TabIndex = 25;
			this.Button8.Text = "Clr";
			this.Button8.UseVisualStyleBackColor = true;
			this.Button9.Location = new global::System.Drawing.Point(485, 230);
			this.Button9.Name = "Button9";
			this.Button9.Size = new global::System.Drawing.Size(32, 20);
			this.Button9.TabIndex = 26;
			this.Button9.Text = "Clr";
			this.Button9.UseVisualStyleBackColor = true;
			this.Button10.Location = new global::System.Drawing.Point(485, 255);
			this.Button10.Name = "Button10";
			this.Button10.Size = new global::System.Drawing.Size(32, 20);
			this.Button10.TabIndex = 27;
			this.Button10.Text = "Clr";
			this.Button10.UseVisualStyleBackColor = true;
			this.Label1.AutoSize = true;
			this.Label1.Location = new global::System.Drawing.Point(12, 9);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(210, 13);
			this.Label1.TabIndex = 130;
			this.Label1.Text = "Enter the text to display for this note object.";
			this.cmOK.Location = new global::System.Drawing.Point(551, 32);
			this.cmOK.Name = "cmOK";
			this.cmOK.Size = new global::System.Drawing.Size(105, 37);
			this.cmOK.TabIndex = 131;
			this.cmOK.Text = "OK";
			this.cmOK.UseVisualStyleBackColor = true;
			this.cmCancel.Location = new global::System.Drawing.Point(551, 77);
			this.cmCancel.Name = "cmCancel";
			this.cmCancel.Size = new global::System.Drawing.Size(105, 37);
			this.cmCancel.TabIndex = 132;
			this.cmCancel.Text = "Cancel";
			this.cmCancel.UseVisualStyleBackColor = true;
			this.cboMode.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cboMode.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboMode.ForeColor = global::System.Drawing.Color.White;
			this.cboMode.FormattingEnabled = true;
			this.cboMode.Location = new global::System.Drawing.Point(125, 295);
			this.cboMode.Name = "cboMode";
			this.cboMode.Size = new global::System.Drawing.Size(105, 21);
			this.cboMode.TabIndex = 11;
			this.Label2.AutoSize = true;
			this.Label2.Location = new global::System.Drawing.Point(10, 300);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(107, 13);
			this.Label2.TabIndex = 134;
			this.Label2.Text = "Text Animation Mode";
			this.Label3.AutoSize = true;
			this.Label3.Location = new global::System.Drawing.Point(10, 325);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(111, 13);
			this.Label3.TabIndex = 135;
			this.Label3.Text = "Text Animation Speed";
			this.cboSpeed.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cboSpeed.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboSpeed.ForeColor = global::System.Drawing.Color.White;
			this.cboSpeed.FormattingEnabled = true;
			this.cboSpeed.Location = new global::System.Drawing.Point(125, 320);
			this.cboSpeed.Name = "cboSpeed";
			this.cboSpeed.Size = new global::System.Drawing.Size(105, 21);
			this.cboSpeed.TabIndex = 12;
			this.Label4.AutoSize = true;
			this.Label4.Location = new global::System.Drawing.Point(10, 350);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(104, 13);
			this.Label4.TabIndex = 137;
			this.Label4.Text = "Animation Hold Time";
			this.cboHoldTime.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cboHoldTime.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboHoldTime.ForeColor = global::System.Drawing.Color.White;
			this.cboHoldTime.FormattingEnabled = true;
			this.cboHoldTime.Location = new global::System.Drawing.Point(125, 345);
			this.cboHoldTime.Name = "cboHoldTime";
			this.cboHoldTime.Size = new global::System.Drawing.Size(105, 21);
			this.cboHoldTime.TabIndex = 13;
			this.tbDelim.BackColor = global::System.Drawing.Color.White;
			this.tbDelim.ForeColor = global::System.Drawing.Color.Black;
			this.tbDelim.Location = new global::System.Drawing.Point(355, 295);
			this.tbDelim.Name = "tbDelim";
			this.tbDelim.Size = new global::System.Drawing.Size(125, 20);
			this.tbDelim.TabIndex = 15;
			this.Label5.AutoSize = true;
			this.Label5.Location = new global::System.Drawing.Point(255, 300);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(99, 13);
			this.Label5.TabIndex = 140;
			this.Label5.Text = "Message Seperator";
			this.cboAlign.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.cboAlign.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboAlign.ForeColor = global::System.Drawing.Color.White;
			this.cboAlign.FormattingEnabled = true;
			this.cboAlign.Location = new global::System.Drawing.Point(125, 370);
			this.cboAlign.Name = "cboAlign";
			this.cboAlign.Size = new global::System.Drawing.Size(105, 21);
			this.cboAlign.TabIndex = 14;
			this.Label6.AutoSize = true;
			this.Label6.Location = new global::System.Drawing.Point(10, 375);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(77, 13);
			this.Label6.TabIndex = 142;
			this.Label6.Text = "Text Alignment";
			this.lbXOff.AutoSize = true;
			this.lbXOff.Location = new global::System.Drawing.Point(255, 325);
			this.lbXOff.Name = "lbXOff";
			this.lbXOff.Size = new global::System.Drawing.Size(69, 13);
			this.lbXOff.TabIndex = 143;
			this.lbXOff.Text = "Text X Offset";
			this.tbXoff.BackColor = global::System.Drawing.Color.White;
			this.tbXoff.ForeColor = global::System.Drawing.Color.Black;
			this.tbXoff.Location = new global::System.Drawing.Point(355, 320);
			this.tbXoff.Name = "tbXoff";
			this.tbXoff.Size = new global::System.Drawing.Size(125, 20);
			this.tbXoff.TabIndex = 16;
			this.lbYoff.AutoSize = true;
			this.lbYoff.Location = new global::System.Drawing.Point(255, 350);
			this.lbYoff.Name = "lbYoff";
			this.lbYoff.Size = new global::System.Drawing.Size(69, 13);
			this.lbYoff.TabIndex = 145;
			this.lbYoff.Text = "Text Y Offset";
			this.tbYoff.BackColor = global::System.Drawing.Color.White;
			this.tbYoff.ForeColor = global::System.Drawing.Color.Black;
			this.tbYoff.Location = new global::System.Drawing.Point(355, 345);
			this.tbYoff.Name = "tbYoff";
			this.tbYoff.Size = new global::System.Drawing.Size(125, 20);
			this.tbYoff.TabIndex = 17;
			this.Button11.Location = new global::System.Drawing.Point(485, 295);
			this.Button11.Name = "Button11";
			this.Button11.Size = new global::System.Drawing.Size(32, 20);
			this.Button11.TabIndex = 28;
			this.Button11.Text = "Clr";
			this.Button11.UseVisualStyleBackColor = true;
			this.Button12.Location = new global::System.Drawing.Point(485, 320);
			this.Button12.Name = "Button12";
			this.Button12.Size = new global::System.Drawing.Size(32, 20);
			this.Button12.TabIndex = 29;
			this.Button12.Text = "Clr";
			this.Button12.UseVisualStyleBackColor = true;
			this.Button13.Location = new global::System.Drawing.Point(485, 345);
			this.Button13.Name = "Button13";
			this.Button13.Size = new global::System.Drawing.Size(32, 20);
			this.Button13.TabIndex = 30;
			this.Button13.Text = "Clr";
			this.Button13.UseVisualStyleBackColor = true;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(682, 417);
			base.Controls.Add(this.Button13);
			base.Controls.Add(this.Button12);
			base.Controls.Add(this.Button11);
			base.Controls.Add(this.tbYoff);
			base.Controls.Add(this.lbYoff);
			base.Controls.Add(this.tbXoff);
			base.Controls.Add(this.lbXOff);
			base.Controls.Add(this.Label6);
			base.Controls.Add(this.cboAlign);
			base.Controls.Add(this.Label5);
			base.Controls.Add(this.tbDelim);
			base.Controls.Add(this.cboHoldTime);
			base.Controls.Add(this.Label4);
			base.Controls.Add(this.cboSpeed);
			base.Controls.Add(this.Label3);
			base.Controls.Add(this.Label2);
			base.Controls.Add(this.cboMode);
			base.Controls.Add(this.cmCancel);
			base.Controls.Add(this.cmOK);
			base.Controls.Add(this.Label1);
			base.Controls.Add(this.Button10);
			base.Controls.Add(this.Button9);
			base.Controls.Add(this.Button8);
			base.Controls.Add(this.Button7);
			base.Controls.Add(this.Button6);
			base.Controls.Add(this.Button5);
			base.Controls.Add(this.Button4);
			base.Controls.Add(this.Button3);
			base.Controls.Add(this.Button2);
			base.Controls.Add(this.Button1);
			base.Controls.Add(this.tbN10);
			base.Controls.Add(this.tbN09);
			base.Controls.Add(this.tbN08);
			base.Controls.Add(this.tbN07);
			base.Controls.Add(this.tbN06);
			base.Controls.Add(this.tbN05);
			base.Controls.Add(this.tbN04);
			base.Controls.Add(this.tbN03);
			base.Controls.Add(this.tbN02);
			base.Controls.Add(this.tbN01);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.Fixed3D;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "frmNotes";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "frmNotes";
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x04000042 RID: 66
		private global::System.ComponentModel.IContainer components;
	}
}
