// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;
using System.Drawing;
using Microsoft.VisualBasic;

namespace MakoCelo.My.Resources
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("MakoCelo.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Afghanistan,AF
        /// Aland Islands,AX
        /// Albania,AL
        /// Algeria,DZ
        /// American Samoa,AS
        /// Andorra,AD
        /// Angola,AO
        /// Anguilla,AI
        /// Antarctica,AQ
        /// Antigua and Barbuda,AG
        /// Argentina,AR
        /// Armenia,AM
        /// Aruba,AW
        /// Australia,AU
        /// Austria,AT
        /// Azerbaijan,AZ
        /// Bahamas,BS
        /// Bahrain,BH
        /// Bangladesh,BD
        /// Barbados,BB
        /// Belarus,BY
        /// Belgium,BE
        /// Belize,BZ
        /// Benin,BJ
        /// Bermuda,BM
        /// Bhutan,BT
        /// Bolivia,BO
        /// Bonaire,BQ
        /// Bosnia and Herzegovina,BA
        /// Botswana,BW
        /// Bouvet Island,BV
        /// Brazil,BR
        /// Indian Ocean,IO
        /// Brunei Darussalam,BN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string country_defs
        {
            get
            {
                return ResourceManager.GetString("country_defs", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ad
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ad", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ae
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ae", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_af
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_af", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ag
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ag", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ai
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ai", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_al
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_al", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_am
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_am", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_an
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_an", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ao
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ao", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ar
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ar", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_as
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_as", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_at
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_at", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_au
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_au", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_aw
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_aw", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ax
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ax", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_az
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_az", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ba
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ba", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_bb
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_bb", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_bd
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_bd", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_be
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_be", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_bf
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_bf", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_bg
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_bg", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_bh
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_bh", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_bi
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_bi", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_bj
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_bj", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_bm
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_bm", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_bn
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_bn", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_bo
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_bo", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_br
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_br", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_bs
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_bs", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_bt
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_bt", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_bv
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_bv", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_bw
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_bw", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_by
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_by", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_bz
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_bz", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ca
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ca", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_catalonia
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_catalonia", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_cc
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_cc", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_cd
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_cd", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_cf
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_cf", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_cg
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_cg", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ch
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ch", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ci
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ci", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ck
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ck", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_cl
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_cl", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_cm
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_cm", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_cn
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_cn", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_co
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_co", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_cr
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_cr", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_cs
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_cs", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_cu
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_cu", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_cv
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_cv", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_cx
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_cx", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_cy
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_cy", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_cz
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_cz", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_de
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_de", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_dj
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_dj", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_dk
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_dk", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_dm
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_dm", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_do
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_do", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_dz
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_dz", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ec
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ec", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ee
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ee", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_eg
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_eg", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_eh
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_eh", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_england
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_england", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_er
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_er", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_es
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_es", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_et
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_et", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_europeanunion
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_europeanunion", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_fam
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_fam", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_fi
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_fi", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_fj
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_fj", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_fk
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_fk", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_fm
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_fm", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_fo
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_fo", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_fr
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_fr", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ga
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ga", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gb
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gb", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gd
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gd", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ge
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ge", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gf
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gf", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gg
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gg", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gh
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gh", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gi
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gi", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gl
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gl", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gm
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gm", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gn
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gn", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gp
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gp", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gq
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gq", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gr
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gr", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gs
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gs", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gt
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gt", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gu
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gu", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gw
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gw", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_gy
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_gy", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_hk
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_hk", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_hm
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_hm", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_hn
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_hn", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_hr
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_hr", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ht
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ht", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_hu
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_hu", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_id
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_id", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ie
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ie", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_il
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_il", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_in
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_in", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_io
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_io", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_iq
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_iq", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ir
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ir", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_is
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_is", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_it
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_it", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_jm
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_jm", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_jo
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_jo", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_jp
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_jp", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ke
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ke", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_kg
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_kg", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_kh
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_kh", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ki
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ki", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_km
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_km", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_kn
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_kn", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_kp
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_kp", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_kr
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_kr", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_kw
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_kw", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ky
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ky", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_kz
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_kz", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_la
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_la", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_lb
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_lb", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_lc
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_lc", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_li
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_li", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_lk
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_lk", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_lr
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_lr", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ls
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ls", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_lt
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_lt", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_lu
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_lu", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_lv
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_lv", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ly
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ly", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ma
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ma", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_mc
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_mc", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_md
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_md", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_me
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_me", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_mg
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_mg", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_mh
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_mh", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_mk
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_mk", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ml
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ml", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_mm
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_mm", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_mn
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_mn", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_mo
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_mo", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_mp
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_mp", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_mq
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_mq", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_mr
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_mr", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ms
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ms", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_mt
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_mt", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_mu
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_mu", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_mv
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_mv", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_mw
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_mw", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_mx
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_mx", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_my
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_my", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_mz
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_mz", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_na
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_na", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_nc
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_nc", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ne
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ne", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_nf
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_nf", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ng
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ng", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ni
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ni", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_nl
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_nl", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_no
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_no", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_np
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_np", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_nr
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_nr", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_nu
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_nu", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_nz
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_nz", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_om
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_om", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_pa
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_pa", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_pe
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_pe", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_pf
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_pf", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_pg
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_pg", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ph
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ph", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_pk
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_pk", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_pl
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_pl", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_pm
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_pm", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_pn
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_pn", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_pr
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_pr", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ps
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ps", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_pt
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_pt", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_pw
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_pw", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_py
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_py", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_qa
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_qa", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_re
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_re", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ro
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ro", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_rs
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_rs", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ru
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ru", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_rw
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_rw", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_sa
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_sa", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_sb
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_sb", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_sc
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_sc", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_scotland
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_scotland", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_sd
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_sd", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_se
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_se", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_sg
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_sg", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_sh
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_sh", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_si
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_si", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_sj
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_sj", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_sk
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_sk", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_sl
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_sl", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_sm
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_sm", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_sn
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_sn", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_so
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_so", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_sr
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_sr", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_st
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_st", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_sv
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_sv", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_sy
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_sy", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_sz
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_sz", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_tc
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_tc", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_td
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_td", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_tf
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_tf", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_tg
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_tg", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_th
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_th", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_tj
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_tj", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_tk
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_tk", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_tl
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_tl", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_tm
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_tm", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_tn
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_tn", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_to
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_to", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_tr
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_tr", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_tt
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_tt", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_tv
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_tv", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_tw
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_tw", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_tz
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_tz", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ua
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ua", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ug
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ug", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_um
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_um", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_us
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_us", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_uy
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_uy", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_uz
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_uz", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_va
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_va", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_vc
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_vc", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ve
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ve", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_vg
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_vg", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_vi
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_vi", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_vn
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_vn", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_vu
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_vu", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_wales
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_wales", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_wf
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_wf", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ws
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ws", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_ye
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_ye", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_yt
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_yt", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_za
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_za", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_zm
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_zm", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flag_zw
        {
            get
            {
                var obj = ResourceManager.GetObject("flag_zw", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        /// {\colortbl ;\red0\green0\blue255;}
        /// {\*\generator Riched20 10.0.19041}\viewkind4\uc1
        /// \pard\sl240\slmult1\b\f0\fs22\lang9 What is MakoCELO\par
        /// \b0 The \i Company of Heroes ELO\i0  (CELO) program was created to give players info about the current Coh2 match they are playing. That program uses web calls to get extended match information and has some built in tools  for non-match related tasks.  MakoCELO is a simplif [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MakoCELO_HelpFile_0446
        {
            get
            {
                return ResourceManager.GetString("MakoCELO_HelpFile_0446", resourceCulture);
            }
        }
    }
}